README.md

The executable seem to expect the model to be in the working directory

Fix run command in README. Fixes #6

---

README.md

No intention for clout-chasing , but I found I couldn't find the `.bin` file when first try to run, so I modified the README to make it a bit more visible.

To make the model bin file more clear in README.

---

gpt4all-backend/scripts/convert_mpt_hf_to_ggml.py

We uploaded an earlier version of the script that didn't add the right things to the ggml file. This is the correct one to use

fix: use right conversion script

---

gpt4all-bindings/python/docs/gpt4all_api.md
gpt4all-bindings/python/docs/gpt4all_modal.md
gpt4all-bindings/python/docs/index.md
gpt4all-bindings/python/mkdocs.yml

Added a section on using modal labs infrastructure with GPT4All

Added modal labs example to documentation

---

gpt4all-chat/CMakeLists.txt
gpt4all-chat/chat.cpp
gpt4all-chat/chat.h
gpt4all-chat/chatlistmodel.cpp
gpt4all-chat/chatlistmodel.h
gpt4all-chat/chatllm.cpp
gpt4all-chat/chatllm.h
gpt4all-chat/llm.cpp
gpt4all-chat/llm.h
gpt4all-chat/main.qml
gpt4all-chat/qml/ChatDrawer.qml
gpt4all-chat/qml/SettingsDialog.qml
gpt4all-chat/server.cpp
gpt4all-chat/server.h

Local OpenAI mirror API webserver impl.

httpserver

---

README.md

Golang Bindings in README

---

gpt4all-chat/CMakeLists.txt
gpt4all-chat/chat.cpp
gpt4all-chat/chatgpt.cpp
gpt4all-chat/chatgpt.h
gpt4all-chat/chatlistmodel.cpp
gpt4all-chat/chatlistmodel.h
gpt4all-chat/chatllm.cpp
gpt4all-chat/chatllm.h
gpt4all-chat/download.cpp
gpt4all-chat/download.h
gpt4all-chat/main.qml
gpt4all-chat/network.cpp
gpt4all-chat/network.h
gpt4all-chat/qml/ModelDownloaderDialog.qml
gpt4all-chat/qml/SettingsDialog.qml
gpt4all-chat/server.cpp

Adamt misc

---

.codespellrc
.github/workflows/codespell.yml
CONTRIBUTING.md
gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-bindings/python/tests/test_pyllmodel.py
gpt4all-chat/README.md
gpt4all-training/train.py

Making gpt4all typo free from now and there on

codespell: config, action + some typos fixed

---

gpt4all-bindings/python/README.md
gpt4all-bindings/python/docs/index.md
gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-bindings/python/mkdocs.yml

- Some small documentation changes to Python bindings (removed google analytics, updated site url, windows installation note)
- Adding sleep to file download to hopefully prevent OS access violations (needs to be tested)

Documentation Updates

---

gpt4all-bindings/cli/app.py
gpt4all-bindings/python/gpt4all/pyllmodel.py

This PR implements a small CLI chat repl. There are small changes made to support this inside of the `pyllmodel.py` but most logic is contained to a new file.
Please let me know if I should make any changes! 
https://github.com/nomic-ai/gpt4all/assets/9896130/5e37bb0e-b774-4261-88b1-6ce214048a69

adds a simple cli chat repl

---

gpt4all-bindings/python/docs/gpt4all_faq.md
gpt4all-bindings/python/docs/gpt4all_python.md
gpt4all-bindings/python/docs/gpt4all_wiki.md
gpt4all-bindings/python/docs/index.md
gpt4all-bindings/python/mkdocs.yml

This PR updates a lot of the documentation on docs.gpt4all.io and introduces an FAQ.

GPT4All Updated Docs and FAQ

---

gpt4all-backend/llamamodel.cpp

Only default mlock on macOS where swap seems to be a problem.

---

.gitignore
gpt4all-bindings/python/docs/index.md

improved documentation landing page

Improved documentation landing page

---

gpt4all-backend/gptj.cpp
gpt4all-backend/gptj.h
gpt4all-backend/llamamodel.cpp
gpt4all-backend/llamamodel.h
gpt4all-backend/llmodel.h
gpt4all-backend/llmodel_c.cpp
gpt4all-backend/mpt.cpp
gpt4all-backend/mpt.h
gpt4all-chat/chatgpt.cpp
gpt4all-chat/chatgpt.h

Llmodel constify

---

gpt4all-chat/CMakeLists.txt
gpt4all-chat/main.qml
gpt4all-chat/qml/MyButton.qml
gpt4all-chat/qml/MyComboBox.qml
gpt4all-chat/qml/SettingsDialog.qml

Start deduplicating the copy+pasta that is our current qml

Start to deduplicate code in qml.

---

README.md

Updated README with improved structure and documentation.

Updated documentation in README.

---

gpt4all-chat/qml/ChatDrawer.qml

Reduced duplicate button code in ChatDrawer.qml, on top of the MyButton and MyComboBox changes
Discussed on Discord

deduplicate qml code

---

gpt4all-chat/CMakeLists.txt
gpt4all-chat/qml/MyCheckBox.qml
gpt4all-chat/qml/MyTextField.qml
gpt4all-chat/qml/SettingsDialog.qml

More duduplication of qml code.
Discussed on Discord.

deduplicate qml: create and use MyCheckBox and MyTextField

---

README.md

Update README.md - very minor typo

---

gpt4all-chat/main.qml
gpt4all-chat/qml/ChatDrawer.qml
gpt4all-chat/qml/ModelDownloaderDialog.qml
gpt4all-chat/qml/MyButton.qml
gpt4all-chat/qml/NetworkDialog.qml
gpt4all-chat/qml/NewVersionDialog.qml
gpt4all-chat/qml/SettingsDialog.qml
gpt4all-chat/qml/ThumbsDownDialog.qml

This PR moves the Accessible.role and Accessible.name properties to MyButton, removes duplications, and adds accessible properties for buttons without them.
Discussed on Discord

dedup qml for buttons, ensure all buttons have accessible properties

---

gpt4all-chat/qml/MyCheckBox.qml

should have caught this - my bad

fix typo so padding can be accessed

---

gpt4all-chat/main.qml

Fixes build break in recent commit

Fix the build.

---

gpt4all-bindings/cli/app.py
gpt4all-bindings/python/gpt4all/gpt4all.py

Many improvements to the Python bindings:
- fix ignoring `--threads=4` (popular default, usually doesn't affect the users)
- cleanup half-downloaded models
- descriptive exceptions
- make code simpler and more pythonic. 
-

Refactor python bindings

---

gpt4all-bindings/python/gpt4all/gpt4all.py

Hotfix - Default verbose for download method in Python bindings

---

gpt4all-training/README.md

Noticed that the docs in the training directory are targeting the wrong repository. Small update to fix the indicated repo.

fix(docs): model repo name

---

gpt4all-backend/llmodel.cpp
gpt4all-backend/llmodel.h

Revert "Improved implementation management code"

---

gpt4all-backend/llmodel.cpp

This MR attempt to implement detection for avxonly being required on the following platforms: Linux/GCC/x86_64, Windows/GCC/x86_64, Windows/MSVC/x86_64.
I know the Linux implementation works, but I need people to test it under Windows!

Advanced avxonly autodetection

---

gpt4all-bindings/python/docs/gpt4all_chat.md

Documentation improvements on LocalDocs (gif, troubleshooting, etc)

Documentation improvements on LocalDocs

---

gpt4all-bindings/golang/Makefile
gpt4all-bindings/golang/README.md
gpt4all-bindings/golang/binding.cpp
gpt4all-bindings/golang/binding.h
gpt4all-bindings/golang/example/main.go
gpt4all-bindings/golang/gpt4all.go
gpt4all-bindings/golang/gpt4all_test.go
gpt4all-bindings/golang/options.go

Note: you need to have *.so files nearby the binary produced by the binding in order to make this to work
```
$ make example/main
$ mv example/main buildllm
$ cd buildllm
$ ./main -m ~/_git/LocalAI/models/ggml-gpt4all-j -t 4
gptj_model_load: loading model from '/home/mudler/_git/LocalAI/models/ggml-gpt4all-j' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
Model loaded successfully.
>>> what's up?
I'm …
```

Golang binding: adapt to support multiple ggml

---

gpt4all-chat/CMakeLists.txt
gpt4all-chat/logger.cpp
gpt4all-chat/logger.h
gpt4all-chat/main.cpp

This PR implements a simple message handler that:
1. Keeps only the previous (and ofc current) log file
2. Logs to stdout on log file creation error

Implemented logging mechanism

---

gpt4all-backend/llmodel.cpp
gpt4all-backend/llmodel.h

This change fixes/explains all current FIXMEs

Cleaned up implementation management

---

gpt4all-bindings/golang/binding.cpp

This is a leftover which otherwise breaks compilation outside of the source

Drop leftover include

---

gpt4all-bindings/golang/gpt4all.go

Add ldl in gpt4all.go for dynamic linking

---

gpt4all-chat/chat.cpp
gpt4all-chat/chat.h
gpt4all-chat/chatllm.cpp
gpt4all-chat/chatllm.h
gpt4all-chat/database.cpp
gpt4all-chat/database.h
gpt4all-chat/localdocs.cpp
gpt4all-chat/localdocs.h
gpt4all-chat/server.cpp

Makes localdocs work with server mode.

Make localdocs work with server mode.

---

gpt4all-backend/llmodel.cpp
gpt4all-backend/llmodel.h
gpt4all-backend/llmodel_c.cpp
gpt4all-backend/llmodel_c.h
gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-bindings/python/gpt4all/pyllmodel.py

Up-to-date Python Bindings

---

gpt4all-backend/gptj.cpp
gpt4all-backend/llamamodel.cpp
gpt4all-backend/mpt.cpp
gpt4all-chat/chat.cpp
gpt4all-chat/chatlistmodel.cpp
gpt4all-chat/chatllm.cpp
gpt4all-chat/chatmodel.h
gpt4all-chat/database.cpp
gpt4all-chat/download.cpp
gpt4all-chat/network.cpp
gpt4all-chat/server.cpp
gpt4all-chat/sysinfo.h

Nothing more to say 😄
Mostly trivial changes.

Fixed tons of warnings and clazy findings

---

gpt4all-backend/llamamodel.cpp

Repeating the change that once was done in https://github.com/nomic-ai/gpt4all/pull/663 but then was overriden by https://github.com/nomic-ai/gpt4all/commit/48275d0dcc0cbd23b7f6469e65b86112a6169dec

Only default mlock on macOS where swap seems to be a problem

---

gpt4all-chat/metadata/models.json

This PR is more about asking for help curating the models.json. I think my descriptions are awful and I need to do a much better job of surfacing relevant information to the end user about what models will meet their needs. The audience for this download dialog should not be an ML researcher, a developer, or someone with a lot of knowledge about open source LLM's, but rather average users who are looking for help deciding which model to download and try: which is quite an investment given the size of these models.
Comments and ideas welcome...

Remove older models that are not as popular.

---

gpt4all-bindings/python/setup.py

Bump pypi version.
Updated pypi package: 
https://pypi.org/project/gpt4all/
Windows test:

Update PyPi version

---

gpt4all-bindings/python/docs/gpt4all_chat.md

Documentation for sideloading models into gpt4all

Documentation for model sideloading

---

gpt4all-bindings/golang/binding.cpp

Otherwise threads count doesn't take effect

Set thread counts after loading model

---

gpt4all-backend/llama.cpp.cmake

This change syncs `llama.cpp.cmake` with upstream llama.cpp `CMakeLists.txt`.
It makes room for:
- metal support
- CUDA/OpenCL support
Although both are untested.
- Will simplify #746; important changes picked up from there
- Will lay some groundwork for #885
And fixes `avxonly` builds still using AVX2.

Synced llama.cpp.cmake with upstream

---

gpt4all-chat/metadata/models.json

Update models json with replit model

---

gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-bindings/python/gpt4all/pyllmodel.py
gpt4all-bindings/python/setup.py
gpt4all-bindings/python/tests/test_gpt4all.py

Method to return a generator for model response. 
How it works: we kick off the C library prompt call in a separate thread so we don't block return of generator. The prompt response callback puts tokens into queue instead of printing them. Generator then dequeues and yields tokens as they are added.

Generator in Python Bindings

---

gpt4all-chat/CMakeLists.txt
gpt4all-chat/main.qml
gpt4all-chat/qml/AboutDialog.qml
gpt4all-chat/qml/Theme.qml
gpt4all-chat/responsetext.cpp
gpt4all-chat/responsetext.h

in responses which is disruptive to code completions in responses.

Add new solution for context links that does not force regular markdown

---

gpt4all-bindings/python/setup.py

version bump setup.py

---

.circleci/continue_config.yml

Updated python workflows to follow @manyoso's circleci patterns with hold approvals and easier pypi deployments.

Updated Python Workflows in CircleCI

---

gpt4all-bindings/python/gpt4all/pyllmodel.py
gpt4all-bindings/python/setup.py

Was not correctly using prompt context. Now it's preserved in class. Fixes, BOS issue.

Bug-fix : Preserve prompt context to fix BOS issue

---

gpt4all-bindings/python/gpt4all/gpt4all.py

Fix 2 spelling typos in gpt4all.py 
No function change. 
https://github.com/nomic-ai/gpt4all/issues/832
- [ x] I have performed a self-review of my code.

Fix spelling typo in gpt4all.py

---

gpt4all-bindings/python/README.md

- Add some notes about common Windows problems when trying to make a local build (MinGW and MSVC).
No direct issue for this docs PR, but I could point to a few where people encountered these problems.
_None_
- Build on Windows without prior knowledge; current `README.md` doesn't provide this information.
If you have feedback, I'd gladly amend/expand on this.
Note: There are several approaches to try and build/get it working with both MinGW and MSVC. I tried to keep the instructions compact and general.

Update python/README.md with troubleshooting info

---

gpt4all-chat/metadata/models.json

- 2 typos
- 1 formatting adjustment to match the others
_None._
_None_
It's mostly a cosmetic change.
_None_

Minor models.json description corrections.

---

gpt4all-bindings/python/setup.py

PyPi Version update for Replit Metal

---

gpt4all-backend/llmodel_c.cpp

Do not specify "success" as error for unsupported models

---

README.md

changed "OSX" to "macOS"

---

gpt4all-bindings/python/docs/gpt4all_chat.md
gpt4all-chat/database.cpp

Afais, it should be sufficient to just add `.org` to the list of supported extensions.
As Org Mode is a clear text format, it should give usable results.

Parse Org Mode files

---

gpt4all-bindings/java/README.md

There were a number of grammatical errors in the README for the Java bindings. This corrects them.

Improve grammar in Java bindings README

---

gpt4all-bindings/cli/README.md
gpt4all-bindings/cli/app.py
gpt4all-bindings/cli/developer_notes.md
gpt4all-bindings/python/docs/gpt4all_cli.md
gpt4all-bindings/python/docs/index.md

Mostly additions to the docs.
- Add gpt4all-bindings/cli/README.md
- Unify version information
- Add gpt4all-bindings/cli/developer_notes.md
- Add gpt4all-bindings/python/docs/gpt4all_cli.md
- Update gpt4all-bindings/python/docs/index.md
- Bump version to 0.3.5, as that is the latest `gpt4all` package on PyPI
- Closes <https://github.com/nomic-ai/gpt4all/issues/646>
- It basically addresses (unless there are other plans), as well: #682 
_None yet_
_None/mostly documentation_
Suggestions welcome.

CLI Improvements

---

gpt4all-backend/replit.cpp

add max_size param to ggml_metal_add_buffer - introduced in https://github.com/ggerganov/llama.cpp/pull/1826

update to latest mainline llama.cpp

---

gpt4all-backend/falcon.cpp

fixes memory leaks copied from ggml/examples based implementation

falcon: use *model-local* eval & scratch bufs

---

gpt4all-backend/CMakeLists.txt
gpt4all-backend/falcon.cpp
gpt4all-backend/gptj.cpp
gpt4all-backend/llmodel_shared.h
gpt4all-backend/mpt.cpp
gpt4all-backend/replit.cpp

prepping to hack on these by hopefully making there be fewer places to fix the same bug

backend: factor out common elements in model code

---

.gitmodules
gpt4all-backend/falcon.cpp
gpt4all-backend/llmodel.h
gpt4all-backend/llmodel_shared.cpp
gpt4all-backend/replit.cpp
gpt4all-bindings/python/gpt4all/tests/test_gpt4all.py
gpt4all-bindings/python/makefile

Enforced that `n_batch` can't go over 128, added python binding tests to check each model type at that input size, adjusted eval buf sizes up by 256mb until they worked
- bindings/python: make target to set up env
- move 230511 submodule to nomic fork, fix alibi assert
- bindings/python: long input tests
- limit prompt batch size to 128
- adjust eval buf sizes to pass long input test
- bindings/python: type assert
- replit: free metal context
- llama.cpp: metal buffer freeing

model memory budget fixes

---

gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-bindings/python/setup.py

Clear chat history between chat sessions

python: Clear chat history between chat sessions

---

gpt4all-bindings/python/docs/gpt4all_python.md
gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-bindings/python/gpt4all/tests/test_gpt4all.py

When streaming tokens in a chat session, you must manually handle collection and updating of the chat history.
```python
from gpt4all import GPT4All
model = GPT4All("orca-mini-3b.ggmlv3.q4_0.bin")
with model.chat_session():
tokens = list(model.generate(prompt='hello', top_k=1, streaming=True))
model.current_chat_session.append({'role': 'assistant', 'content': ''.join(tokens)})
tokens = list(model.generate(prompt='write me a poem about dogs', top_k=1, streaming=True))
model.current_chat_session.append({'role': 'assistant', 'content': ''.join(tokens)})
print(model.current_chat_session)
```

Python chat streaming

---

gpt4all-chat/responsetext.cpp

implemented highlighting in the chat client for bash and go
Bash:
Go:
ask gpt to write a script in go or bash

implemented support for bash and go highlighting rules

---

gpt4all-chat/responsetext.cpp

created highlighting rules for json formatted file and c# code
json:

json and c# highlighting rules

---

gpt4all-chat/chatllm.cpp
gpt4all-chat/mysettings.cpp
gpt4all-chat/qml/ApplicationSettings.qml

Provide some guardrails for thread count.

---

gpt4all-backend/llmodel.cpp

see https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-isprocessorfeaturepresent
(uploading to check it builds on CI, don't push if it doesn't!)

windows/msvc: use high level processor feature detection API

---

gpt4all-chat/chatllm.cpp
gpt4all-chat/metadata/models.json

System prompts

---

gpt4all-bindings/java/README.md
gpt4all-bindings/java/TODO.md
gpt4all-bindings/java/pom.xml
gpt4all-bindings/java/src/main/java/com/hexadevlabs/gpt4all/LLModel.java

Make sure model file is both found and readable to java  before letting backend load it.
To solve issue https://github.com/nomic-ai/gpt4all/issues/1167
- [x ] I have performed a self-review of my code.

Java binding - Improve error check before loading Model file

---

README.md

The main readme has installer links, too. So it makes sense to make the AVX/AVX2 requirement visible here.
_None_
_None_
_None_
_None_

Add AVX/AVX2 requirement to main README.md

---

gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-chat/modellist.h

TopP 0.1 was found to be somewhat too aggressive, so a more moderate default of 0.4 would be better suited for general use.
- [*] I have performed a self-review of my code.
- [*] I have tagged PR with relevant project labels. I acknowledge that a PR without labels may be dismissed.

Update default TopP to 0.4

---

.circleci/continue_config.yml

fix continue_config.yml

---

gpt4all-bindings/typescript/index.cc
gpt4all-bindings/typescript/package.json

Better error handling and display for nodejs users

Refactor(typescript)/error handling

---

gpt4all-chat/mysettings.cpp
gpt4all-chat/mysettings.h
gpt4all-chat/qml/ApplicationSettings.qml
gpt4all-chat/qml/Theme.qml

added aa button to switch color modes and check functionality between light mode and dark mode
https://github.com/nomic-ai/gpt4all/assets/58596666/5668fd2a-dd65-4b7b-b250-1d610f194de7
click on settings, application settings, change theme
possible future features are more color based mode like a blue based mode or adding detection of system color as default color scheme

light mode vs dark mode

---

gpt4all-api/docker-compose.gpu.yaml

Pin Huggingface Inference Server to Apache 2 Version

---

gpt4all-bindings/python/gpt4all/pyllmodel.py

This is a follow-up to the PR https://github.com/nomic-ai/gpt4all/pull/867 which was left unfinished. I've implemented a buffer of bytes that gets filled until it can be decoded into a string. Most of the credit goes to the previous PR. 
However, there is an issue that can be seen in the pastebin from the demo section. Something goes wrong with the bytes of an emoji and the rest of the messages doesn't get decoded. This can be fixed by "cutting out" the bad emoji leaving a "?" in its place and decoding the rest of the message without it. But why does a bad emoji happen in the first place? It's just the model being dumb or I'm missing something?
**Update 27.07:** In the new commit, the buffer is split into space-separated chunks. If the generation of a chunk was finished, but it wasn't …

Python bindings: unicode decoding

---

gpt4all-bindings/python/README.md
gpt4all-bindings/python/docs/gpt4all_faq.md
gpt4all-bindings/python/docs/gpt4all_python.md
gpt4all-bindings/python/gpt4all/__init__.py
gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-bindings/python/gpt4all/pyllmodel.py
gpt4all-bindings/python/gpt4all/tests/test_embed_timings.py
gpt4all-bindings/python/gpt4all/tests/test_gpt4all.py
gpt4all-bindings/python/mkdocs.yml

- Add Release build hint to Readme.
- Documentation overhaul: extend Python docs and update with information on the last big PR.
- black & isort linting in Python bindings.
- Move Chat GUI out of the Bindings group in the docs navigation.
_None_
_None_
mainly: `make documentation` 😉
Comments welcome. Especially if something can be rearranged or made more clear & concise. I've been at it for a while.

Python Clean-Up Pass

---

gpt4all-chat/main.qml
gpt4all-chat/qml/ChatDrawer.qml

fixed scrollbar issue with main chat. The issue was that scrollview and listview both have internal scroll functionality. So I turned off scrollview's scroll functionality and used listview's scroll functionality instead.
Issue #1291 
https://github.com/nomic-ai/gpt4all/assets/58596666/4af86076-47da-40a8-9d28-eb32704011bc
type a lot of things in main chat

scrollbar fixed for main chat and chat drawer

---

gpt4all-chat/metadata/models.json

Add LLaMA2 7B model to model.json.

---

gpt4all-chat/main.qml
gpt4all-chat/mysettings.cpp
gpt4all-chat/mysettings.h
gpt4all-chat/qml/AboutDialog.qml
gpt4all-chat/qml/ApplicationSettings.qml
gpt4all-chat/qml/ChatDrawer.qml
gpt4all-chat/qml/CollectionsDialog.qml
gpt4all-chat/qml/LocalDocsSettings.qml
gpt4all-chat/qml/ModelDownloaderDialog.qml
gpt4all-chat/qml/ModelSettings.qml
gpt4all-chat/qml/MyButton.qml
gpt4all-chat/qml/MySettingsStack.qml
gpt4all-chat/qml/MySettingsTab.qml
gpt4all-chat/qml/MyToolButton.qml
gpt4all-chat/qml/NetworkDialog.qml
gpt4all-chat/qml/NewVersionDialog.qml
gpt4all-chat/qml/SettingsDialog.qml
gpt4all-chat/qml/StartupDialog.qml
gpt4all-chat/qml/Theme.qml
gpt4all-chat/qml/ThumbsDownDialog.qml

added a dropdown in application settings to allow of transition of fontsize from small, medium, and large.
#986 #647 #488 
https://github.com/nomic-ai/gpt4all/assets/58596666/a5d31239-f304-4fe7-ae2e-430ab031858a
change font size in application settings

font size changer and updates

---

gpt4all-api/gpt4all_api/app/api_v1/routes/embeddings.py
gpt4all-api/gpt4all_api/app/tests/test_endpoints.py

Added an endpoint similar to the completion endpoints that matches OpenAI OpenAPI spec and loads Embed4All into memory
ref: https://twitter.com/andriy_mulyar/status/1682204779357896704?s=20

Add embeddings endpoint

---

gpt4all-chat/README.md

Updated README.md with a wishlist idea

---

.circleci/continue_config.yml
gpt4all-bindings/typescript/src/util.js
gpt4all-bindings/typescript/test/gpt4all.test.js

fix ts tests on windows

---

README.md

Added the Weaviate integration to the README file.
Only updated the README file

Add Weaviate integration

---

gpt4all-bindings/python/README.md

Python bindings readme example with GPU support.

Update Python bindings README.md

---

gpt4all-chat/chatllm.cpp

fixes issues w/ multiple of the same gpu

init at most one vulkan device, submodule update

---

gpt4all-backend/llamamodel.cpp
gpt4all-backend/llamamodel_impl.h
gpt4all-backend/llmodel.h
gpt4all-chat/chat.cpp
gpt4all-chat/chat.h
gpt4all-chat/chatllm.cpp
gpt4all-chat/chatllm.h
gpt4all-chat/main.qml

Show a specific warning in the GUI when a GPU device was chosen but was not used.

chat: report reason for fallback to CPU

---

gpt4all-chat/CMakeLists.txt

I forgot to uncomment these lines when I finished GPT-J support.

cmake: install the GPT-J plugin

---

gpt4all-bindings/python/gpt4all/gpt4all.py

python: always check status code of HTTP responses

---

gpt4all-bindings/python/gpt4all/gpt4all.py

file in models2.json has no `ggml-` prefix
https://discordapp.com/channels/1076964370942267462/1093558720690143283/1161778216462192692

fix embed4all filename

---

gpt4all-bindings/java/src/main/java/com/hexadevlabs/gpt4all/LLModel.java
gpt4all-bindings/java/src/test/java/com/hexadevlabs/gpt4all/BasicTests.java

- [ x] I have performed a self-review of my code.
- [ x] If it is a core feature, I have added thorough tests.
- [ x] I have added thorough documentation for my code.

Improves Java API signatures maintaining back compatibility

---

gpt4all-bindings/cli/app.py
gpt4all-bindings/python/gpt4all/pyllmodel.py

python: replace deprecated pkg_resources with importlib

---

gpt4all-chat/README.md

Updated chat wishlist

---

gpt4all-backend/llama.cpp.cmake

more mat*mat ops, prompt processing on gpu

---

gpt4all-chat/build_and_run.md

Add written instructions to the build how-to.
Fixes #1514

docs: improve build_and_run.md

---

gpt4all-bindings/csharp/README.md
gpt4all-bindings/python/README.md
gpt4all-bindings/python/docs/gpt4all_typescript.md
gpt4all-bindings/typescript/README.md
gpt4all-chat/build_and_run.md

docs: clarify Vulkan dependency in build instructions for bindings

---

gpt4all-api/gpt4all_api/Dockerfile.buildkit
gpt4all-bindings/java/README.md
gpt4all-bindings/python/docs/gpt4all_typescript.md
gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-bindings/typescript/README.md
gpt4all-bindings/typescript/src/gpt4all.d.ts
gpt4all-bindings/typescript/src/util.js
gpt4all-chat/download.cpp

The new models reside in the 'gguf' folder.

update default model URLs

---

gpt4all-bindings/python/setup.py

GGUF Python Release

---

gpt4all-chat/main.qml

chat: fix syntax error in main.qml

---

gpt4all-bindings/cli/README.md
gpt4all-bindings/python/README.md
gpt4all-bindings/python/docs/gpt4all_cli.md
gpt4all-bindings/python/docs/gpt4all_python.md
gpt4all-bindings/python/docs/index.md
gpt4all-bindings/python/gpt4all/tests/test_gpt4all.py
gpt4all-bindings/typescript/spec/chat.mjs

ref https://github.com/nomic-ai/gpt4all/pull/1502#issuecomment-1773911185

bindings: replace references to GGMLv3 models with GGUF

---

README.md

README: add clear note about new GGUF format

---

gpt4all-bindings/cli/app.py

app.py: change default model to Mistral Instruct

---

gpt4all-bindings/typescript/README.md

Updated readme for correct install instructions

---

gpt4all-chat/metadata/models2.json

This adds Microsoft's Orca 2 models, quantized by TheBloke:
- https://huggingface.co/TheBloke/Orca-2-7B-GGUF
- https://huggingface.co/TheBloke/Orca-2-13B-GGUF

models2.json: add Orca 2 models

---

gpt4all-bindings/golang/README.md

N/A
Steps outlined in readme
Does not work without the recursive step. Other bindings have this added, so i copied the format

include recursion, copied from csharp

---

gpt4all-bindings/cli/app.py

Adding a typer option for the device parameter in the GPT4ALL class by modifying the REPL function. This allows to choose cpu, cuda and GPU per https://docs.gpt4all.io/gpt4all_python.html#api-documentation
- [] If it is a core feature, I have added thorough tests.
- Pull the latest code from the branch.
- Run the app.py script using the command: python app.py repl --device=gpu
- Observe the model running on the specified GPU device.

Update app.py - Adding GPU support and syntax

---

gpt4all-backend/llamamodel.cpp

Explicitly clear the kv cache each time we eval tokens to match n_past.

---

.circleci/config.yml
.circleci/continue_config.yml

This should avoid the need for dummy commits like this https://github.com/nomic-ai/gpt4all/commit/f8564398fc67211b85d8e23860b09c0036cd7eb7
when I make a change like this https://github.com/nomic-ai/gpt4all/commit/b96406669dc8bb59155a0bb20ef802654703a26e

ci: run all workflows on config change

---

gpt4all-chat/build_and_run.md

make QT and related packages installation easier for Fedora users who are building gpt4all-chat from source

add fedora command for QT and related packages

---

gpt4all-api/README.md

The readme recommends changing the files in "api" directory, which does not exists. The correct folder is "app".
Open [nomic-ai/gpt4all/gpt4all-api/README.md and 
](https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-api#spinning-up-your-app) and read "and edit files in the api directory." paragraph.

Update API guidance

---

gpt4all-bindings/python/docs/gpt4all_chat.md

docs: update list of supported localdocs formats

---

.circleci/continue_config.yml
gpt4all-bindings/csharp/Gpt4All.Samples/Gpt4All.Samples.csproj
gpt4all-bindings/csharp/Gpt4All.Tests/Gpt4All.Tests.csproj
gpt4all-bindings/csharp/Gpt4All/Gpt4All.csproj

Nuget for .NET

---

gpt4all-bindings/python/setup.py

Add project links and the README file to the Python package that gets published to PyPI.
Refs:
- #1963

README and project links for PyPI listing

---

gpt4all-chat/main.qml

Simple solution to try and fix issue #1905

Save the window size for the user and reuse next load.

---

gpt4all-chat/modellist.cpp

s/contextLength/gpuLayers/
Fixes #2010

modellist: fix bad copy-paste in ModelList::clone

---

gpt4all-backend/llmodel_shared.cpp
gpt4all-bindings/python/docs/gpt4all_python.md
gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-chat/metadata/models3.json
gpt4all-chat/modellist.h

Before, the model was seeing this for Alpaca-style chat sessions:
```
Question?
Answer###User:
Follow-up question
```
With this PR, the model sees this:
```
Question?
Answer
Follow-up question
```

llmodel: default to a blank line between reply and next prompt

---

gpt4all-bindings/python/gpt4all/gpt4all.py

mypy found a missing function argument, also complains about \_\_func\_\_ which we can silence because it's a false positive.

python: fix mistakes from PR #1970

---

gpt4all-backend/llmodel_c.cpp
gpt4all-backend/llmodel_c.h
gpt4all-bindings/python/gpt4all/_pyllmodel.py

This feature was requested by the developers of the typescript bindings.

llmodel_c: expose fakeReply to the bindings

---

gpt4all-chat/chat.cpp
gpt4all-chat/chat.h
gpt4all-chat/chatgpt.cpp
gpt4all-chat/chatllm.cpp
gpt4all-chat/chatllm.h
gpt4all-chat/main.qml
gpt4all-chat/modellist.cpp
gpt4all-chat/network.cpp

It's simple but it does the job. The popup is easily dismissed by clicking basically anywhere, so it's not too intrusive.

chat: implement display of model loading warnings

---

gpt4all-backend/llamamodel.cpp
gpt4all-bindings/python/docs/gpt4all_python.md
gpt4all-bindings/python/gpt4all/_pyllmodel.py
gpt4all-bindings/python/gpt4all/gpt4all.py
gpt4all-bindings/python/gpt4all/tests/test_gpt4all.py
gpt4all-bindings/typescript/src/config.js
gpt4all-chat/metadata/models3.json

See the commits for more info. I put the word "breaking" in the title of changes that change the API in some way and may need further scrutiny.

python: various fixes for GPT4All and Embed4All

---

.circleci/continue_config.yml

fix failing workflow

---

.circleci/continue_config.yml

fix with npm install --ignore-scripts again

---

gpt4all-chat/metadata/models2.json
gpt4all-chat/metadata/models3.json

I have added the Ghost 7B v0.9.1 model to the support list.
Nice to see it will be merged and officially used soon.
Model at HuggingFace:
- Base: https://huggingface.co/lamhieu/ghost-7b-v0.9.1
- GGUF: https://huggingface.co/lamhieu/ghost-7b-v0.9.1-gguf
Thanks for review !

Support Ghost 7B v0.9.1 gguf

---

gpt4all-bindings/python/gpt4all/gpt4all.py

python: also delete partial file on KeyboardInterrupt/SystemExit

---

gpt4all-chat/qml/ChatView.qml

Include links for Documentation and FAQ for new users on the "new chat view".
Before:  
After:  
Documentation link goes here:  
FAQ link goes here:  
Co-authored-by: ThiloteE <73715071+ThiloteE@users.noreply.github.com>

Include links for Documentation and FAQ for new users on the "new chat view".

---

gpt4all-backend/llamamodel.cpp
gpt4all-bindings/python/setup.py

- Allow increased n_ctx to actually allow multiple sequences to be submitted in one forward pass
- Don't crash when llama_tokenize returns no tokens

embed4all: small fixes related to nomic client local embeddings

---

gpt4all-chat/metadata/models2.json
gpt4all-chat/metadata/models3.json

This system prompt is based on the [recommended one](https://huggingface.co/Open-Orca/Mistral-7B-OpenOrca#prompt-template), but it can lead to strange results, as seen in #2198.

models.json: use simpler system prompt for Mistral OpenOrca

---

README.md

Creates a readme section for the 2024 roadmap.

Roadmap update

---

gpt4all-chat/network.cpp

This should fix the MSVC build. It compiles on Windows, at least.
Follow-up to #2238

network: fix use of GNU asm statement with MSVC

---

gpt4all-backend/llmodel.cpp
gpt4all-backend/llmodel.h
gpt4all-chat/network.cpp

It would be useful to know how many users are relying on our "avxonly" build of llama.cpp.

mixpanel: report cpu_supports_avx2 on startup

---

README.md

Until now, I don't think we've ever actually documented the difference between the two types of installers.
ref #2333

readme: document difference between installers

---

gpt4all-bindings/python/README.md

Fix a wrong path for installation of python bindings

Fix path in Readme

---

gpt4all-chat/chatapi.cpp
gpt4all-chat/chatllm.cpp
gpt4all-chat/chatllm.h
gpt4all-chat/download.cpp
gpt4all-chat/embeddings.cpp
gpt4all-chat/embllm.cpp
gpt4all-chat/logger.cpp
gpt4all-chat/main.cpp
gpt4all-chat/modellist.cpp
gpt4all-chat/modellist.h
gpt4all-chat/mysettings.cpp
gpt4all-chat/mysettings.h
gpt4all-chat/network.cpp
gpt4all-chat/server.cpp

This is just a refactor with no intended functional changes.
Note that the target branch is major_new_ui_redesign.

[NEW UI] chat: refactor mysettings + other cleanup

---

gpt4all-chat/metadata/release.json

Final release notes for v3.0.0.

release.json: update release notes for v3.0.0

---

gpt4all-bindings/python/docs/gpt4all_desktop/cookbook/use-local-ai-models-to-privately-chat-with-google-drive.md

formatted note callouts

---

gpt4all-bindings/python/mkdocs.yml

Add analytic entry

---

gpt4all-chat/database.cpp

Provide case insensitive matching of localdocs file extensions.

Fix for issue #2609.

---

MAINTAINERS.md

Adding Jeremy Tayco to the maintainers list as per his e-mail.
Follow-up to #2654

maintainers: add jstayco

---

gpt4all-chat/metadata/models3.json

Included llama 3.1 8b instruct 
modified order for all models (MPT chat has two, needs attention.)
set each parameter as needed.
Made small changes.
- define the old llama 3 as 8b
- Change Nous Hermes Mistral 7b DPO to "good" from best.
- Suggest you look at MPT chat dual entries.

updated models3.json

---

gpt4all-chat/metadata/models3.json

Models json 310 Lowercase hash

---

gpt4all-chat/translations/gpt4all_zh_CN.ts

Update gpt4all_zh_CN.ts, fix some not translated ,to merge

---

gpt4all-chat/README.md

Updates Readme.md of gpt4all-chat
- updates features
- removes feature wish-list
- removes any mention of gpt-j since support for it has been removed with https://github.com/nomic-ai/gpt4all/pull/2676
1. Remove potential cause for duplication and conflicts between documentation on website and the wiki.
2. Readme should be future proof, so handle wish-list and roadmap via issue tracker.

Chat readme: Updates features and removes wish-list & gpt-j

---

gpt4all-bindings/python/docs/gpt4all_python/monitoring.md

The Monitoring doc seems to have changed from my previous commit so this PR just adds some missing context and words in the Doc
cc @cebtenzzre

[Docs]: Updating Monitoring Doc

---

gpt4all-chat/translations/gpt4all_zh_CN.ts

Update gpt4all_zh_CN.ts some not translated

---

gpt4all-chat/translations/gpt4all_it_IT.ts

Updated the Italian localization file as requested before official release.
Added missing strings
Unless other changes will be required, this is the currently finalized Italian localization. I will review it from time to time, or when I will discover corrections to be made.

Updated Italian localization file

---

gpt4all-chat/translations/gpt4all_it_IT.ts

Italian localization update

---

gpt4all-chat/CHANGELOG.md

Add a Changelog to the repo that we can maintain as we merge PRs to make it easier to publish release notes for new versions of the chat UI.

chat: add CHANGELOG.md

---

gpt4all-chat/translations/gpt4all_ro_RO.ts

The translated text for the interface of v3.1.1+ 
has been updated as to be shown correctly in the language: Romanian - ro_RO
2024.08.09
6x "unfinished" texts were translated
Diacritics were all placed in their proper places.

TRANSLATION: GUI: into ROMANIAN: file: gpt4all_ro_RO.ts

---

gpt4all-chat/translations/gpt4all_es_MX.ts

Updated es_MX translation.
Column on left in HomeView isn't wide enough to accommodate the extra letters required by just a tiny bit.

Updated es_MX translation

---

gpt4all-chat/translations/gpt4all_es_MX.ts

Updated requested strings to better fit the overall main menu asthetic.

Small fixes for better main menu UI

---

gpt4all-chat/translations/gpt4all_ro_RO.ts

"LocalDocs" left as it is, an Essential term within the program.
Most of multiline texts (as they appear in text editors like Notepad) combined into single-lines.
The "chat/s" term - deleted and /replaced with the word in RO

GPT4All +v3.1.1: GUI: TRANSLATION: into ro_RO

---

gpt4all-bindings/python/setup.py

I forgot to change this for the v2.8.1 release.
Related to #2802

python: fix CUDA dependency version

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/translations/gpt4all_ro_RO.ts

Several lowercased, misplaced diacritics were corrected.

Translation-Update gpt4all_ro_RO.ts-corrected a few mis-LCased diacritics

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/qml/ChatView.qml
gpt4all-chat/translations/gpt4all_en_US.ts
gpt4all-chat/translations/gpt4all_es_MX.ts
gpt4all-chat/translations/gpt4all_it_IT.ts
gpt4all-chat/translations/gpt4all_pt_BR.ts
gpt4all-chat/translations/gpt4all_ro_RO.ts
gpt4all-chat/translations/gpt4all_zh_CN.ts
gpt4all-chat/translations/gpt4all_zh_TW.ts

The LocalDocs sources currently display "_ Sources" regardless of number.
Brought up in [Discord](https://discord.com/channels/1076964370942267462/1090427154141020190/1274456399631356056).
I've edited it on GitHub itself, ~~but if you want I can try to go and update the translation files, too~~, then made it work locally in the `en_US` translation.

Update ChatView.qml to enable numerusform for "%n Source(s)"

---

README.md

Also reorganizes the important links to put more above the video.
The download links are now in their own section that uses less vertical space and has information about system requirements.
Closes #2894

readme: add blog link

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/llm.cpp

Direct update button to offline installer releases page.
Replaced the url to direct the offline_installer to a useful page.

Update button for offline installer now points to releases.

---

gpt4all-chat/src/qml/ApplicationSettings.qml
gpt4all-chat/translations/gpt4all_en_US.ts
gpt4all-chat/translations/gpt4all_es_MX.ts
gpt4all-chat/translations/gpt4all_it_IT.ts
gpt4all-chat/translations/gpt4all_pt_BR.ts
gpt4all-chat/translations/gpt4all_ro_RO.ts
gpt4all-chat/translations/gpt4all_zh_CN.ts
gpt4all-chat/translations/gpt4all_zh_TW.ts

Don't think this needs a changelog entry.

Change the name here to be more descriptive.

---

README.md
gpt4all-bindings/python/docs/gpt4all_desktop/quickstart.md

Updates docs to include youtube tutorial link

Add youtube tutorial link to docs.

---

gpt4all-chat/translations/gpt4all_es_MX.ts

Ran lupdate command to update strings for 3.3.0. Only content changes found were vanished strings that remained in the file. This removes those.
Command ran for reference: `lupdate  ../ -locations absolute -no-obsolete -ts ./gpt4all_es_MX.ts`

Small es_MX update for 3.3.0

---

gpt4all-bindings/python/docs/gpt4all_api_server/home.md
gpt4all-bindings/python/docs/gpt4all_desktop/settings.md
gpt4all-bindings/python/mkdocs.yml

Docs section & page for the GPT4All API server

Docs section & page for the GPT4All API server

---

.circleci/continue_config.yml

PR #2722 missed a few jobs. See this failed workflow: https://app.circleci.com/pipelines/github/nomic-ai/gpt4all/3502/workflows/9665bc81-e347-4df0-919e-cf4fa1ab2454/jobs/19549

ci: fix build timeouts

---

README.md
gpt4all-chat/qml/HomeView.qml

Moving newsletter link to nomic.ai/gpt4all and away from tally form.

Move newsletter link

---

README.md
gpt4all-chat/qml/HomeView.qml

Makes form links point to anchors.

Update README.md with form anchor

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/src/chatmodel.h
gpt4all-chat/src/xlsxtomd.cpp

Add the attached filename to the model's context.

---

gpt4all-chat/translations/gpt4all_ro_RO.ts

Translated the new strings for v3.4.0 that were marked as "unfinished".

Update gpt4all_ro_RO.ts after v3.3.1 for v3.4.0

---

gpt4all-chat/metadata/latestnews.md
gpt4all-chat/metadata/release.json

This PR updates the release notes and latest news for the new release.

chat: release version 3.4.0

---

gpt4all-bindings/python/docs/gpt4all_desktop/cookbook/use-local-ai-models-to-privately-chat-with-microsoft-excel.md

Added a video of xlsx attachment to the Excel Cookbook

xlsx video

---

gpt4all-chat/metadata/latestnews.md

latestnews: add notice about regression

---

gpt4all-chat/metadata/latestnews.md
gpt4all-chat/metadata/release.json

~~Leaving as draft pending upload of installers.~~
Installers are uploaded. ~~Updates.xml has not yet been pushed.~~ Done.

chat: release v3.4.2

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/src/database.cpp

Found problems when investigating #3138.
The example document I used to find these problems and fix is attached here [foo.docx](https://github.com/user-attachments/files/17522565/foo.docx)

Fixup docx parsing

---

gpt4all-chat/CHANGELOG.md

I remembered that there were a few functional side-effects to the Jinja PR in the API server and remote model functionality.

changelog: add more changes from #3147

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/translations/gpt4all_ro_RO.ts

2024.12.07-GPT4All 3.4.2x. GUI - Translation to ro_RO
The updated file with the translation to ro_RO (Romanian).
Author: Victor Emanuel of SINAPSA Infocomplex(R)(TM)

2024.12.07- for GPT4All v3.5.0. - Translation into ro_RO (Romanian)

---

gpt4all-chat/translations/gpt4all_ro_RO.ts

Updated the ro_RO language file.

2024.12.13 - translation: Update gpt4all_ro_RO.ts

---

gpt4all-chat/metadata/latestnews.md
gpt4all-chat/metadata/release.json

Do not merge until the installers have been uploaded.

chat: release version 3.5.2

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/src/chatmodel.h

These became reversed in #3147. That's my bad.

chatmodel: fix sources showing as unconsolidated in UI

---

gpt4all-bindings/python/docs/gpt4all_desktop/settings.md

fix: format of language and locale setting

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/src/codeinterpreter.cpp
gpt4all-chat/src/codeinterpreter.h

This is related to issue #3355

Properly report that the computation was timedout to the model

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/src/codeinterpreter.cpp

A more flexible alternative to #3341.
Closes #3341

code interpreter: support variadic console.log

---

README.md

Update README.md - brokenlink

---

gpt4all-chat/CHANGELOG.md
gpt4all-chat/qml/ChatView.qml

Will add changelog as soon as it is determined what release this will target.

Server view fix

---

gpt4all-chat/translations/gpt4all_it_IT.ts
gpt4all-chat/translations/gpt4all_zh_CN.ts

The Italian translation has been reviewed by Harvester62.

Italian and draft Simplified Chinese translations for v3.10.0

---

gpt4all-chat/metadata/latestnews.md
gpt4all-chat/metadata/release.json

Blocked on:
- ~~Offline installers~~
- ~~Online installers~~

chat: release version 3.10.0
