README.md
adding double quote below allows running this in the terminal without manually adding it in the command line.
=> fix typo in generate example command

README.md
`git clone git@github.com:nomic-ai/gpt4all.git` yield `Permission denied`
```sh
git clone --recurse-submodules git@github.com:nomic-ai/gpt4all.git
Cloning into 'gpt4all'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
=> Change git clone url to https://github.com/nomic-ai/gpt4all.git to avoid `Permission denied`

README.md
`git submodule configure` isn't a valid command. I assume the intended command is `init`, which can be combined with `update` using the `--init` option.
=> Fix `git submodule` instructions

data.py
Fixing the following bug:
```python
File "/mnt/storage7T/gpt4all/data.py", line 73, in load_data
dataset = dataset.train_test_split(test_size=.05, seed=config["seed"])
AttributeError: 'DatasetDict' object has no attribute 'train_test_split'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/storage7T/gpt4all/train.py:207 in <module>                                                  │
│                                                                                                  │
│   204 │   else:                                                                                  │
│   205 │   │   accelerator = Accelerator()                                                        │
│   206 │ …
```
=> DatasetDict to dataset object.

README.md
Added additional OS terminal commands to readme for the unfiltered bin:
M1 Mac/OSX: cd chat;./gpt4all-lora-quantized-OSX-m1 -m gpt4all-lora-unfiltered-quantized.bin
Linux: cd chat;./gpt4all-lora-quantized-linux-x86 -m gpt4all-lora-unfiltered-quantized.bin
Windows (PowerShell): cd chat;./gpt4all-lora-quantized-win64.exe -m gpt4all-lora-unfiltered-quantized.bin
Intel Mac/OSX: cd chat;./gpt4all-lora-quantized-OSX-intel -m gpt4all-lora-unfiltered-quantized.bin
=> adds to README.md

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
TIL a single PR template must be in .github folder.
Added label tagging warning in all templates.
=> Label Tag Warning and Fix 2 to PR Template

gpt4all-backend/gptj.cpp, gpt4all-backend/llamamodel.cpp, gpt4all-backend/mpt.cpp
Caught with AddressSanitizer running a basic prompt test against llmodel standalone. This fix allows ASan builds to complete a simple prompt without illegal accesses but there are still notably several leaks.
=> backend: fix buffer overrun in repeat penalty code

.github/workflows/close_issues.yml
Limited issues are fetched from github api. We need to paginate through all pages and have number of issues set to 100 rather than 30.
=> Paginate through all issues for close_issues workflow

gpt4all-bindings/golang/gpt4all.go
When using the golang bindings, cgo includes in `gpt4all.go` are relative, this makes any use of the bindings outside of the gpt4all repository fail.
This PR adds `$(SRCDIR)` to the includes so they are absolute.
This fixes issue: #614 
- [x ] I have performed a self-review of my code.
- [ x] If it is a core feature, I have added thorough tests.
- [ x] I have added thorough documentation for my code.
- [x ] I have tagged PR with relevant project labels. I acknowledge that a PR without labels may be dismissed.
- [X ] If this PR addresses a bug, I have provided both a screenshot/video of the original bug and the working solution.
Include the bindings in a new golang project.
Try to build:
```
$ make main 
C_INCLUDE_PATH=/Users/XXX/code/src/github.com/XXX/intelligens/include \ …
```
=> Fix #614, where relative paths to includes makes go builds fail

gpt4all-backend/llamamodel.cpp
Defaults mlock to always true. According to discord:
gonzochess75
why is it default to off?
eachadea
it makes model loading a bit slower sometimes, but mlock has no disadvantages otherwise
eachadea
it's more stable by ensuring the model is always in RAM
and not swapped unless there is truly no RAM available
=> Always default mlock to true.

gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-bindings/python/gpt4all/pyllmodel.py
Fix occurrences of the prompt callback being incorrectly specified, or the response callback's prototype being incorrectly used in its place.
Discussed earlier on Discord.
=> llmodel: fix wrong and/or missing prompt callback type

gpt4all-bindings/csharp/.gitignore, gpt4all-bindings/csharp/Gpt4All.Tests/Constants.cs, gpt4all-bindings/csharp/Gpt4All.Tests/Gpt4All.Tests.csproj, gpt4all-bindings/csharp/Gpt4All.Tests/ModelFactoryTests.cs, gpt4all-bindings/csharp/Gpt4All.sln
Create a `Gpt4All.Tests` project to hold unit tests for the C# bindings.
Since the API is rapidly evolving right now, it only tests loading the three different types of models.
Help is welcome.
The plan is to eventually test the whole C# bindings library.
=> An initial set of tests for the C# bindings

gpt4all-backend/llmodel.cpp, gpt4all-backend/llmodel.h
This change improves the way llmodel handles the different available build variants by:
* Moving static functions into `LLModel` class
* Seperating implementation list from `get_implementation()` (now `LLModel::getImplementation()`)
* Allowing to `getBuildVariantList()` (for GUI)
=> Improved implementation management code

gpt4all-chat/server.cpp
The json response body of the web server's
endpoint "POST /v1/chat/completions" is adhering to the openAi api schema
issue #753 
**not a core feature**
**The change makes the application behave consistenlty with the current documentation.**
**i think i do not have permission to attach labels on the PR. github does not provide me the option to do so**
**no changes in GUI.**
described in the relevant issue
=> fix issue #753

gpt4all-backend/dlhandle.h, gpt4all-bindings/csharp/build_win-mingw.ps1, gpt4all-bindings/csharp/build_win-msvc.ps1
There is one file that was missing a `#define NOMINMAX` when including the windows.h header. This was causing the msvc build to fail, since because the order of operations of how, I believe, it was being compiled, it would include the min/max headers that would break "std::min" and "std::max"
No, I don't get why that is the case.
Adding the definition fixed it.
While I was here, I updated the build scripts to also pull in the new DLLs being generated.
=> Fix MSVC Build, Update C# Binding Scripts

gpt4all-chat/qml/SettingsDialog.qml
the defaults that we have right now aren't ideal, i tried many models(nous-vicuna, snoozy, groovy....) with the values given here: https://www.reddit.com/r/LocalLLaMA/wiki/index/#wiki_prompting , i used the "Precise" preset, and all of the models gave much better results.
Amount of times the models got stuck in a loop writing the same thing over and over significantly decreased using the new values, that allowed to make them write more longer responses, and follow the conversation for longer, without going schitzo.
And i believe the newcomers will appreciate not having to figure out why the models are constantly getting stuck in loops whenever the conversation gets a little long.
Also changed the `batch size` from `9` to `128`, 9 is too conservative imo.
=> Change the default values for generation in GUI

.gitmodules, gpt4all-backend/CMakeLists.txt, gpt4all-backend/llama.cpp.cmake, gpt4all-backend/llamamodel.cpp, gpt4all-backend/llmodel.cpp, gpt4all-chat/CMakeLists.txt
todos:
* built by default on mac now
* detected and now falling back to default impl
this only curently does anything for llama ggmlv3 models. Metal (and ggml GPU offload generally) requires some additional support on the model code side to move stuff in and out of GPU memory (well, Metal on M1/M2 does unified memory so its simpler than say, CUDA), and in addition to the current q4_0 quant limitation, only a subset (the subset needed to run llama) of the ggml ops are currently implemented in Metal. Notably missing for supporting our other models are
* GELU activation (most models use this, but llama uses swish)
* ALiBi positional bias (MPT, Replit)
* regular old layernorm (llama uses RMSNorm)
=> llama on Metal

.gitmodules, gpt4all-backend/CMakeLists.txt, gpt4all-backend/llama.cpp.cmake, gpt4all-backend/llamamodel.cpp, gpt4all-backend/llmodel.cpp, gpt4all-bindings/python/setup.py, gpt4all-chat/CMakeLists.txt
Python binding works now `ggml-metal.metal` is now searched for next to the .so/.dylib by adding https://github.com/ggerganov/llama.cpp/pull/1782 to our fork, the `.metal` file needs to generally be copied along with the llmodel libs with this approach.
=> Metal+LLama take two

gpt4all-backend/llama.cpp.cmake
- A bug introduced in 0cb2b86730a56cee7460b0582418228e8049d3ef breaks AVX on Windows with MSVC
- currently getting: `warning C5102: ignoring invalid command-line macro definition '/arch:AVX2'`
- The solution is to use `_options(...)` not `_definitions(...)`
- https://github.com/nomic-ai/gpt4all/issues/923
Description of the problem is in the accompanying issue: #923 
Build on Windows without the fix produces warnings like:
```
command line : warning C5102: ignoring invalid command-line macro definition '/arch:AVX2' ...
```
=> Fix Windows MSVC AVX builds

.codespellrc, gpt4all-bindings/java/src/main/java/com/hexadevlabs/gpt4all/LLModel.java
Fix typo in javadoc,
Add word to ignore list for codespellrc
=> Typo, ignore list 

gpt4all-backend/gptj.cpp, gpt4all-backend/gptj_impl.h, gpt4all-backend/llamamodel.cpp, gpt4all-backend/llamamodel_impl.h, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_shared.cpp, gpt4all-backend/mpt.cpp, gpt4all-backend/mpt_impl.h, gpt4all-backend/replit.cpp, gpt4all-backend/replit_impl.h, gpt4all-chat/chatgpt.h
fixes a definite use-after-free and likely avoids some other
potential ones - std::string will convert to a std::string_view
automatically but as soon as the std::string in question goes out of
scope it is already freed and the string_view is pointing at freed
memory - this is *mostly* fine when its returning a reference to the
tokenizer's internal vocab table but it's, imo, too easy to return a
reference to a dynamically constructed string with this as replit is
doing (and unfortunately needs to do to convert the internal whitespace
replacement symbol back to a space)
=> llmodel: change tokenToString to not use string_view

gpt4all-backend/CMakeLists.txt, gpt4all-backend/replit.cpp
works now
TODOs:
* will be fixed by https://github.com/nomic-ai/gpt4all/pull/968
* can't easily dynamically resize buffers when using `metal`, once a buffer has been `ggml_metal_add_buffer`'d to the `ggml_metal_context` it is there for the remaining life of the `ggml_metal_context`, so scrap the `mem_per_token` stuff and just lower the memory requirement altogether by using scratch buffers
=> metal replit

gpt4all-backend/dlhandle.h
use RTLD_LOCAL so that symbols are *only* exposed via dlsym
without this all symbols exported by the libs are available for symbol
resolution, resulting in different lib versions potentially resolving
*each other's* symbols, causing incredibly cursed behavior such as
https://gist.github.com/apage43/085c1ff69f6dd05387793ebc301840f6
=> dlhandle: prevent libs from using each other's symbols

gpt4all-bindings/golang/README.md, gpt4all-bindings/golang/gpt4all.go, gpt4all-bindings/golang/options.go
This is used to identify the path where all the various implementations are
This adds `SetLibrarySearchPath` as model option to search lib path in the specified directory instead of the current work directory.
#826 
Before:
```
11:59AM DBG Loading model in memory from file: /home/mudler/_git/LocalAI/models/ggml-gpt4all-j                                                                                                                       
Debug: New GPT4ALL                                                                                                                                                                                                          
Debug: Library search path: /tmp/localai/backend_data …
```
=> Allow to set a SetLibrarySearchPath in the golang bindings

gpt4all-backend/CMakeLists.txt
- it turns out this bug exists upstream if you do what we do and set `n_ctx` to 2048: https://github.com/ggerganov/llama.cpp/issues/1881
=> fix llama.cpp k-quants

gpt4all-backend/gptj.cpp, gpt4all-backend/mpt.cpp, gpt4all-backend/replit.cpp, gpt4all-backend/utils.h
This cleans up the code a very tiny bit by removing the `MB` variable from each implementation and instead having an `operator ""_MiB` in `utils.h`.
=> Use operator ""_MiB instead of defining MB in each implementation

gpt4all-bindings/cli/app.py
The CLI app.py is currently broken. See discussion starting in this issue here: <https://github.com/nomic-ai/gpt4all/issues/820#issuecomment-1582955946>
- the bindings API changed in 057b9, but the CLI was not updated
- change 'std_passthrough' param to the renamed 'streaming'
- remove '_cli_override_response_callback' as it breaks and is no longer needed
The bug was discovered as part of a separate/wider issue: https://github.com/nomic-ai/gpt4all/issues/820#issuecomment-1582955946
- bug traceback see: <https://github.com/nomic-ai/gpt4all/issues/820#issuecomment-1582955946>
- fixed version (Windows cmd):
try to run, it'll break:
```shell
python -m pip install --user -U gpt4all typer  # installs current gpt4all==0.3.0
python gpt4all-bindings/cli/app.py repl
```
I did not yet increase the …
=> Fix CLI app.py

gpt4all-chat/qml/ModelDownloaderDialog.qml
To not show every little tiny network spike to the user
=> Update download speed less often

gpt4all-chat/server.cpp
Add the `Access-Control-Allow-Origin` header to the chat GUI's web API to enable [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).
It was mentioned in <https://github.com/nomic-ai/gpt4all/issues/941> _"Introduce a button in the UI Settings to enable CORS for the Web Server Mode of GPT4ALL UI."_
Using the following example HTML document:
```html
<html><head><title>CORS test</title></head>
<body>
<script type="text/javascript">
function foo() {
console.log("start click handler");
function xhrHandler(e) {
console.log("handled.")
console.log(e);
};
var xhr = new XMLHttpRequest();
xhr.addEventListener("load", xhrHandler);
xhr.open("GET", "http://localhost:4891/v1/models");
xhr.send();
console.log("end click handler");
}
</script>
<input type="button" onclick="foo()" value="click …
```
=> Allow Cross-Origin Resource Sharing (CORS)

.circleci/continue_config.yml
avoid spurious failures due to apt cache being out of date
=> CI: apt update before apt install

gpt4all-bindings/python/gpt4all/gpt4all.py
Change **python bindings**
Added possibility to set number of cpu threads `n_threads` directly in class GPT4All, when instantiating.
`mpt = gpt4all.GPT4All(model_name = "ggml-mpt-7b-chat",  model_path = "D:/00613/nomic.ai/GPT4all", allow_download=False, n_threads=6)`
It seems to me, that the class GPT4All works as an interface to the python user. So the python user should be able to set the number of threads directly with a method of GPT4All.
#1029 Add the possibility to set the number of CPU threads (n_threads) with the python bindings
when instantiating.
=> set n_threads in GPT4All python bindings

gpt4all-chat/qml/SettingsDialog.qml
Changed "Enable web server:" to "Enable API server:"
Found a few of new people confusing Web server with a WebUI, with this change it should be clearer as to what this setting does.
- [*] I have performed a self-review of my code.
- [*] If it is a core feature, I have added thorough tests.
=> Change "web server" to "API server" for less confusion

gpt4all-chat/CMakeLists.txt
The patch include support for running natively on a Linux Wayland display server/compositor which is successor to old Xorg. Cmakelist was missing WaylandClient so added it back.
This will fix #1047 .
Although I have tested it at my end, this PR should be reviewed properly in all configurations before merging.
=> Enable Wayland in build

gpt4all-backend/gptj.cpp, gpt4all-backend/gptj_impl.h, gpt4all-backend/llamamodel.cpp, gpt4all-backend/llamamodel_impl.h, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-backend/mpt.cpp, gpt4all-backend/mpt_impl.h, gpt4all-backend/replit.cpp, gpt4all-backend/replit_impl.h, gpt4all-bindings/python/gpt4all/pyllmodel.py, gpt4all-chat/chatgpt.cpp, gpt4all-chat/chatgpt.h
most of these can just shortcut out of the model loading logic 
llama is a bit worse to deal with because we submodule it so I have to at least parse the hparams, and then I just use the size on disk as an estimate for the mem size (which seems reasonable since we mmap() the llama files anyway)
tested via added method in python binding (`.gpt4all` is a symlink to my actual model dir)
```python
from pathlib import Path
from gpt4all import pyllmodel
models = list((Path.home() / '.gpt4all').glob('*.bin'))
llm = pyllmodel.LLModel()
allsizes = {}
for model in models:
print(f'get size for {model}: ', end='')
sz = llm.memory_needed(str(model))
print(f'{sz}')
allsizes[model.name] = sz
print(allsizes)
```
=> add requiredMem method to llmodel impls

gpt4all-chat/main.cpp, gpt4all-chat/main.qml, gpt4all-chat/mysettings.cpp, gpt4all-chat/mysettings.h, gpt4all-chat/qml/SettingsDialog.qml
is necessary to get rid of technical debt before we drastically increase the complexity of settings by adding per model settings and mirostat and other fun things. Right now the settings are divided between QML and C++ and some convenience methods to deal with settings sync and so on that are in other singletons. This change consolidates all the logic for settings into a single class with a single API for both C++ and QML.
=> Start moving toward a single authoritative class for all settings. This

gpt4all-chat/responsetext.cpp
Added highlighting rules for the gpt4all chat for the java programming language so that it is easier to read the code the models are producing
ask the chat to write a java program
=> created highlighting rules for java using regex for the gpt4all chat

gpt4all-backend/gptj.cpp, gpt4all-backend/mpt.cpp
should reduce required eval memory for these model types and makes all of our models reserve eval memory in the same way (almost - some still do the mem_per_token thing and some don't - next task is to unify that behavior)
- backend/gptj: use scratch buffers
- backend/mpt: use scratch bufs
- fix format-related compile warnings
=> Use ggml scratch bufs for mpt and gptj models

gpt4all-bindings/python/gpt4all/gpt4all.py
so that codespell doesn't start yelling at everyone again
=> bindings/python: fix typo

gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/gpt4all/pyllmodel.py, gpt4all-bindings/python/makefile
Fixes some (not all) of the typechecking complaints I get editing these files
with a linter enabled.
- python: do not mutate locals()
- python: fix (some) typing complaints
- python: queue sentinel need not be a str
- python: make long inference tests opt in
=> python bindings: typing fixes, misc fixes

gpt4all-chat/responsetext.cpp
Makes it so the codeblock is output in a monospaced font which is suitable for code (for readability)
https://github.com/nomic-ai/gpt4all/issues/1026
~- If it is a core feature, I have added thorough tests.~ (not a core feature)
After:
Before:
Prompt: `﻿Write a simple hello world in python`
Nothing of note
=> Monospace text for codeblocks

gpt4all-bindings/cli/app.py
- Adapted to Python bindings API changes
- Version selection based on package information
- Does not currently work with `1.0.1` however, as it's not fully implemented:
```
NotImplementedError: Streaming tokens in a chat session is not currently supported.
```
- Does, however, work with `main`.
- in the meantime, someone reported it as: #1123 
(Commited version doesn't include the message `version 1.0.1, using new loop`)
- CLI is currently broken with Python bindings v1.0.0 & v1.0.1; just try to run it
- ~~This PR won't fix that yet, but it should once streaming with chat session is supported.~~ It is and it works.
- Alternative ideas to fix it? Maybe I didn't understand the new API completely?
- It's mostly a hack for now in any case. Fixing it is first priority, we can talk about …
=> Fix CLI to work with 1.x.y version of the Python bindings

gpt4all-api/gpt4all_api/app/api_v1/routes/completions.py, gpt4all-api/gpt4all_api/app/tests/test_endpoints.py, gpt4all-api/gpt4all_api/requirements.txt
Adding the ability to do streaming requests to the "/completions" endpoint of the API. Added in a test to showcase using the openai python client to stream the response from the api.
This addresses the NotImplementedError in the completions route of the api
https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-api/gpt4all_api/app/api_v1/routes/completions.py#L54
```python
model = "gpt4all-j-v1.3-groovy"
prompt = "Who is Michael Jordan?"
for resp in openai.Completion.create(
model=model,
prompt=prompt,
max_tokens=50,
temperature=0.28,
top_p=0.95,
n=1,
echo=True,
stream=True):
print(resp.choices[0].text)
```
The above results in the model output being streamed to your console, directly from the API
There is a great issue thread over on the openai-node library page, discussing a lot of this …
=> GPT4All API: Add Streaming to the Completions endpoint

.circleci/continue_config.yml, gpt4all-chat/CMakeLists.txt
Adds [Qt6::WaylandCompositor](https://doc.qt.io/qt-6/qwaylandcompositor.html) to cmakelist to make the GPT4ALL chat interface runnable natively on a Linux Wayland session.
This time only it only adds for the Linux Builds.
To make this PR work, we need to add [Qt6::WaylandCompositor](https://doc.qt.io/qt-6/qwaylandcompositor.html) in circleci config. Unless that is done, this PR will result in build failure.
=> Enable Wayland support only to Linux Build

.gitignore, gpt4all-bindings/java/.gitignore, gpt4all-bindings/java/Developer_docs.md, gpt4all-bindings/java/README.md, gpt4all-bindings/java/pom.xml, gpt4all-bindings/java/src/main/java/com/hexadevlabs/gpt4all/LLModel.java, gpt4all-bindings/java/src/main/java/com/hexadevlabs/gpt4all/Util.java
The bindings version changed to 1.1.4
Update Java bindings to be compatible with gpt4all 2.4.11
falcon model support.
Developer docs included for Java bindings with instructions on how to build Java bindings.
=> Java bindings update with support for gpt4all 2.4.11

gpt4all-chat/modellist.cpp
QDirIterator doesn't seem subdir aware, its path() returns
the iterated dir. This was the simplest way I found to get this right.
=> Correctly find models in subdirs of model dir

gpt4all-backend/llmodel.cpp
- fix Windows MSVC arch detection in llmodel.cpp
- to fix AVX-only handling
there are several now. probably all of these are about the same bug:
- #965
- #1009 
- #1060 
- #1084
- #1097
- #1175 
Windows MSVC compiler doesn't have `__x86_64__` for x86-64, but instead: `_M_X64`
Hope this finally fixes that.  😅
=> Fix Windows MSVC arch detection

gpt4all-chat/responsetext.cpp
Created highlighting rules to make is easier for users to intake code in html, php, and latex
HTML:
PHP:
LaTeX:
groovy model, write some [language] code
=> highlighting rules for html and php and latex

gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/gpt4all/tests/test_gpt4all.py
- Custom callbacks & session improvements PR (v1.0.6) had one too many checks.
- Remove the problematic config['url'] check.
- Add a crude test, which will download the embeddings model into a temporary directory and verify.
- Fixes #1261.
- #1261 
Run test, it works:
Currently, the following won't download a model, if not already present. For example try the following; but it's not limited to the embeddings model. Any model not hosted on an external site (i.e. with a full URL in `models.json`) is affected:
```py
from gpt4all import Embed4All
e4a = Embed4All()
```
For now, there's a simple test which actually downloads the model into a temporary directory. I hope I can refine that at some point.
=> Fix models not getting downloaded in Python bindings

gpt4all-api/gpt4all_api/app/api_v1/routes/completions.py
Previously, we passed around the same dict object and only updated the `inputs` key/value in the dictionary. But since the call is async, the call would only run with the same dictionary object across all elements in the batch. This creates a new dictionary object for each call to the async function. 
- [ x ] I have performed a self-review of my code.
- [] If this PR addresses a bug, I have provided both a screenshot/video of the original bug and the working solution.
=> Fixes batched GPU inference

gpt4all-api/gpt4all_api/app/api_v1/settings.py, gpt4all-api/gpt4all_api/app/main.py
Adds an optional flag into the gpt4all-api start-up that allows you to monitor the API with sentry.
=> Allow you to monitor GPT4All-API with Sentry

gpt4all-backend/llmodel.cpp
- Replace high-level `IsProcessorFeaturePresent`
- Reintroduce low-level compiler intrinsics implementation
- #1288
_None_
- Try to run GPT4All on an outdated Windows version. It'll fail with the catch-all model load error despite having AVX/AVX2.
- See the comments in linked issue (from [here](https://github.com/nomic-ai/gpt4all/issues/1288#issuecomment-1667241169)); the [test script](https://gist.github.com/cosmic-snow/6c93526ea4c8b5428def2bf63d6be390) returns `False` for all AVX checks even if present.
It's quite unfortunate how this all came to be. The previous low-level code was changed in an attempt to fix the Windows AVX-only problem, but that ultimately turned out be caused by an incomplete pre-processor macro. That in turn masked this problem.
The (potential) fix here …
=> Fix Windows unable to load models on older Windows builds

gpt4all-backend/llama.cpp.cmake
=> fix msvc compilation on windows with vulkan

gpt4all-bindings/python/README.md
Running `git clone --recurse-submodules git@github.com:nomic-ai/gpt4all.git` returns `Permission denied (publickey)` as shown below:
```
git clone --recurse-submodules git@github.com:nomic-ai/gpt4all.git
Cloning into gpt4all...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
This change replaces `git@github.com:nomic-ai/gpt4all.git` with `https://github.com/nomic-ai/gpt4all.git` which runs without permission issues.
resolves nomic-ai/gpt4all#8, resolves nomic-ai/gpt4all#49
=> Replace git clone SSH URI with HTTPS URL

gpt4all-chat/flatpak-manifest/io.gpt4all.gpt4all.appdata.xml, gpt4all-chat/flatpak-manifest/io.gpt4all.gpt4all.desktop, gpt4all-chat/flatpak-manifest/io.gpt4all.gpt4all.yml
Add flatpak manifest for building flatpaks on Linux
Refer: #698 
Testers and reviews welcome! You will need  org.kde.Sdk 6.5 and org.freedesktop.Sdk.Extension.node14 for it to build. Please do install it before running flatpak-builder.
=> Add flatpak manifest

gpt4all-backend/llamamodel.cpp, gpt4all-backend/llmodel.h, gpt4all-chat/chatllm.cpp
Instead of a terse message with the prefix "Using CPU", word each message to clearly indicate that there was an issue that prevents GPU acceleration from being used.
=> chat: clearer CPU fallback messages

gpt4all-chat/metadata/models2.json
Added the just-released EM German Mistral Model to `models2.json`.
You can find more information, example outputs and so on in [the models repository](https://github.com/jphme/EM_German/tree/main). The model comes with the Apache-2.0 license of the base model.
TBH, I still don't understand 100% how GPT4ALL`s model list works (I suppose its still based on a proprietary hosted model list?); the model wasn't available for download in the model list when I rebuild GPT4all, but I confirmed that the [model works falwlessly](https://drive.google.com/file/d/1T6AIhtew4K3fQMDKiOBT6YIeM2m7rpVa/view) within the most recent app.
I asked in Discord and they said I should just prepare a PR.
Reson for this is I am the author of the most-downloaded llama-2 model finetuned on German texts and people kept …
=> Add support for EM German Mistral Model

.github/ISSUE_TEMPLATE/bug-report.yml
This section is often not used correctly (left blank or wrong boxes checked), and it is redundant since maintainers can select the relevant labels anyway, which can be seen at a glance and used to filter issues.
=> issue template: remove "Related Components" section

gpt4all-chat/chat.cpp, gpt4all-chat/chatlistmodel.cpp, gpt4all-chat/chatllm.cpp, gpt4all-chat/chatllm.h, gpt4all-chat/chatmodel.h
This restores the state from a file even if the model is missing for instance. This is necessary for the new release since all the models will have changed. This will also enable a new feature in an upcoming commit where we have a new setting for always restoring state from text instead of via kvcache so as to limit disk usage.
=> Restore state from text

gpt4all-chat/chatllm.cpp
I saw this while building with Visual Studio. It seems like a good idea to initialize responseLogits before serializing it, even if its value isn't used anywhere.
=> chatllm: do not write uninitialized data to stream

gpt4all-bindings/python/gpt4all/gpt4all.py
This makes it easier to use the GPT4All interface from Python with arbitrary paths, which may be of type pathlib.Path instead of a string.
=> python: support Path in GPT4All.__init__

gpt4all-backend/llmodel.cpp
This makes it clearer to users of the bindings when they are trying to run them on an unsupported CPU:
```
Found model file at ./orca-mini-3b.q4_0.gguf
LLModel ERROR: CPU does not support AVX
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/local/lib/python3.11/site-packages/gpt4all/gpt4all.py", line 96, in __init__
self.model.load_model(self.config["path"])
File "/usr/local/lib/python3.11/site-packages/gpt4all/pyllmodel.py", line 266, in load_model
raise ValueError(f"Unable to instantiate model: code={err.code}, {err.message.decode()}")
ValueError: Unable to instantiate model: code=45, Model format not supported (no matching implementation found)
```
(The ERROR line is the new one.)
=> llmodel: print an error if the CPU does not support AVX

gpt4all-backend/llamamodel.cpp, gpt4all-bindings/python/gpt4all/gpt4all.py
* disable llama.cpp logging unless GPT4ALL_VERBOSE_LLAMACPP envvar is nonempty
* make verbose flag for retrieve_model default false (but also be overridable via gpt4all constructor)
should be able to run a basic test:
```python
import gpt4all
model = gpt4all.GPT4All('/Users/aaron/Downloads/rift-coder-v0-7b-q4_0.gguf')
print(model.generate('def fib(n):'))
```
and see no non-model output when successful
=> make python bindings quiet by default

gpt4all-chat/chat.cpp, gpt4all-chat/chat.h, gpt4all-chat/chatlistmodel.cpp, gpt4all-chat/chatlistmodel.h, gpt4all-chat/mysettings.cpp, gpt4all-chat/mysettings.h, gpt4all-chat/network.cpp, gpt4all-chat/network.h, gpt4all-chat/qml/ApplicationSettings.qml
This also changes the UI behavior to always open a 'New Chat' and setting it as current instead of setting a restored chat as current. This improves usability by not requiring the user to wait if they want to immediately start chatting.
=> always save chats to disk, but save them as text by default

gpt4all-backend/llama.cpp.cmake
so far my from-scratch mat\*mats are still (a good bit) slower than just running more invocations of the existing Metal ported mat\*vec shaders
it should be theoretically possible to make a mat\*mat that's faster (for actual mat\*mat cases) than an optimal mat\*vec, but it will need to be at *least* as fast as the mat\*vec op and then take special care to be cache-friendly and save memory bandwidth, as the # of compute ops is the same - don't have this figured out yet so this is better for now
=> speedup: just use mat*vec shaders for mat*mat

gpt4all-backend/llama.cpp.cmake
Follow-up to https://github.com/nomic-ai/llama.cpp/pull/8.
Fixes this error from the python bindings:
```
OSError: libkp_logger.so: cannot open shared object file: No such file or directory
```
=> kompute: fix library loading issues with kp_logger

.circleci/continue_config.yml
I tried to install from pip on OS X 10.13 High Sierra and got "load command 0x80000034 is unknown" while trying to load a .dylib. This corresponds to the LC_DYLD_CHAINED_FIXUPS command, which is only available as of OS X 10.15 (see [10.14 SDK](https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX10.14.sdk/usr/include/mach-o/loader.h#L313), [10.15 SDK](https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX10.15.sdk/usr/include/mach-o/loader.h#L324)).
related to #70 (although that issue mainly refers to the chat client)
=> CI: increase minimum macOS version of Python bindings to 10.15

.circleci/continue_config.yml, gpt4all-backend/llama.cpp.cmake, gpt4all-bindings/csharp/README.md, gpt4all-bindings/csharp/build_win-mingw.ps1, gpt4all-bindings/python/setup.py, gpt4all-bindings/typescript/scripts/build_mingw.ps1
This PR bumps the version of the python bindings to 2.0.0rc1, and fixes the CircleCI Windows build.
=> python: prepare version 2.0.0rc1

gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/gpt4all/pyllmodel.py
The smaller fixes:
- print verbose messages to stderr instead of stdout
- support finding llmodel.dll for MSVC builds, which is not called libllmodel.dll
The larger change here is that we will now attempt to resume interrupted downloads. @apage43 and I have both run into flaky connections with the server the models are hosted on, and this should improve the situation.
Tested by using psutil to suspend/resume the process, causing the sever to close the connection due to a timeout. It is now able to resume where it left off, and the sha256sum checks out:
```
>>> x = GPT4All('orca-mini-3b-gguf2-q4_0.gguf')
13%|███████████████▊                                                                                                           | 254M/1.98G [12:10<1:12:32, 397kiB/s]
Download interrupted, …
```
=> python: connection resume and MSVC support

gpt4all-backend/llamamodel.cpp, gpt4all-bindings/python/setup.py
This will be important once #1515 is merged:
```
>>> from gpt4all import GPT4All
>>> x = GPT4All('mpt-7b.Q4_0.oldbpe.nodup.nomerges.gguf', model_path='.', allow_download=False)
error loading model: cannot find tokenizer merges in model file
llama_load_model_from_file: failed to load model
LLAMA ERROR: failed to load model from ./mpt-7b.Q4_0.oldbpe.nodup.nomerges.gguf
>>>
```
Without this change, only the LLAMA ERROR line would be printed by default.
=> llamamodel: re-enable error messages by default

gpt4all-chat/main.qml, gpt4all-chat/qml/ApplicationSettings.qml, gpt4all-chat/qml/ChatDrawer.qml, gpt4all-chat/qml/LocalDocsSettings.qml, gpt4all-chat/qml/ModelDownloaderDialog.qml, gpt4all-chat/qml/MySettingsTab.qml, gpt4all-chat/qml/NetworkDialog.qml, gpt4all-chat/qml/SettingsDialog.qml, gpt4all-chat/qml/StartupDialog.qml
This will make the speech output less verbose for screen reader users.
=> Removed extraneous and shortened text in accessibility name and description fields

gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/setup.py
I forgot to change this from .bin to .gguf for the new model format.
=> python: change default extension to .gguf

gpt4all-backend/llmodel.cpp
this fixes some issues that were being seen on installed windows builds of 2.5.0
only load dlls that actually might be model impl dlls, otherwise we pull all sorts of random junk into the process before it might expect to be
This is #1546 minus the intialization order changes
=> llmodel: whitelist library name patterns

gpt4all-backend/bert.cpp, gpt4all-backend/gptj.cpp, gpt4all-backend/llamamodel.cpp
I don't think GGUFv3 is actually a different format on little-endian CPUs, but because of the version bump we have to update the version numbers accordingly.
I cherry-picked the [GGUFv3 PR](https://github.com/ggerganov/llama.cpp/pull/3552) into the llama.cpp submodule anyway, so we will have to merge [this branch](https://github.com/nomic-ai/llama.cpp/tree/ggufv3) into our llama.cpp fork as well.
=> backend: support GGUFv3

gpt4all-chat/build_and_run.md
Only the Qt HTTP Server and Qt PDF libraries (and their implied dependencies) are needed, as far as I know. This could save the user a significant amount of disk space.
=> build_and_run: clarify which additional Qt libs are needed

gpt4all-backend/llamamodel.cpp, gpt4all-backend/llmodel.cpp, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-bindings/golang/Makefile, gpt4all-bindings/golang/binding.cpp, gpt4all-bindings/java/src/main/java/com/hexadevlabs/gpt4all/LLModel.java, gpt4all-bindings/java/src/main/java/com/hexadevlabs/gpt4all/LLModelLibrary.java, gpt4all-bindings/python/gpt4all/pyllmodel.py, gpt4all-bindings/typescript/index.cc
I've seen quite a few user reports that just have an error message like "ValueError: Unable to instantiate model" or "ValueError: Unable to instantiate model: code=34, Numerical result out of range" when they are e.g. just trying to load a model that has too new of a GGUF version.
The error code is often ERANGE because many floating point operations can set errno. errno really shouldn't be checked unless it is immediately after a failed system call.
I added some printing to cases in llamamodel.cpp that should only be seen when there is a fatal problem loading the model file. This should help actually understand what is happening when there is a failure.
(Note: I haven't tested the changes to the go, Java, and typescript bindings, there could be syntax errors.)
=> llmodel_c: improve quality of error messages

gpt4all-backend/gptj.cpp, gpt4all-backend/llama.cpp.cmake, gpt4all-backend/llamamodel.cpp, gpt4all-backend/llmodel.h
NOTE: Requires this llama.cpp branch, which is where most of the changes are: https://github.com/nomic-ai/llama.cpp/tree/update-llamacpp-base
We will have to reset our llama.cpp fork's master branch to that commit before we can properly merge this.
What I did:
- Split the Vulkan changes into their own branch: https://github.com/nomic-ai/llama.cpp/tree/vulkan
- Incrementally merged the latest llama.cpp into them (up to https://github.com/ggerganov/llama.cpp/commit/6b0a7420), making commits as needed to maintain parity between Metal and Vulkan. This is the current state of the vulkan branch.
- Merged the vulkan branch into the GPT4All-specific branch, and made several changes on top of that. This is update-llamacpp-base.
- Updated the llama.cpp dependency in GPT4All and made the necessary …
=> Update to latest llama.cpp

gpt4all-backend/bert.cpp, gpt4all-backend/gptj.cpp
The GGML API changed the way graphs are allocated, and #1706 broke Bert because I didn't notice this.
This fixes the floating point exception with Bert and GPT-J models.
=> backend: use ggml_new_graph for GGML backend v2

gpt4all-backend/CMakeLists.txt, gpt4all-backend/llmodel.cpp, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_shared.cpp, gpt4all-chat/CMakeLists.txt, gpt4all-chat/mysettings.cpp
Isolate the AVX2 libraries from the platform-independent ones again by loading llamamodel-mainline-*.so when we need to list the available GPU devices. (This does assume we only try to keep one version of llama.cpp around - hopefully we plan to keep it that way?)
Confirmed working on my AVX2 machine with an AMD GPU - the chat UI starts for once, *and* the GPU is correctly displayed in the list of devices.
I'm not sure why chat was directly linking to Bert because it builds fine without that link, even with `-Wl,--no-undefined`.
I also removed "llama" from the library regex since there is no matching library - the closest one is llamamodel-mainline, which is already listed.
Fixes #1674
=> fix AVX support by removing direct linking to AVX2 libs

gpt4all-chat/server.cpp
"created" is supposed to be an int64, not a string. Returning 0 makes them valid, though still useless. Addresses issue https://github.com/nomic-ai/gpt4all/issues/1353
=> Update server.cpp to return valid created timestamps

gpt4all-chat/build_and_run.md
I actually tried to follow these instructions on an Arch Linux system with minimal graphical components, and realized that I missed a few things.
=> docs: add missing dependencies to Linux build instructions

gpt4all-chat/CMakeLists.txt, gpt4all-chat/main.qml, gpt4all-chat/qml/AboutDialog.qml, gpt4all-chat/qml/ApplicationSettings.qml, gpt4all-chat/qml/ChatDrawer.qml, gpt4all-chat/qml/CollectionsDialog.qml, gpt4all-chat/qml/LocalDocsSettings.qml, gpt4all-chat/qml/ModelDownloaderDialog.qml, gpt4all-chat/qml/ModelSettings.qml, gpt4all-chat/qml/MyBusyIndicator.qml, gpt4all-chat/qml/MyButton.qml, gpt4all-chat/qml/MyCheckBox.qml, gpt4all-chat/qml/MyComboBox.qml, gpt4all-chat/qml/MyDialog.qml, gpt4all-chat/qml/MyDirectoryField.qml, gpt4all-chat/qml/MySettingsButton.qml, gpt4all-chat/qml/MySettingsDestructiveButton.qml, gpt4all-chat/qml/MySettingsLabel.qml, gpt4all-chat/qml/MySettingsStack.qml, gpt4all-chat/qml/MySettingsTab.qml, gpt4all-chat/qml/MySlug.qml, gpt4all-chat/qml/MyTextArea.qml, gpt4all-chat/qml/MyToolButton.qml, gpt4all-chat/qml/NetworkDialog.qml, gpt4all-chat/qml/NewVersionDialog.qml, gpt4all-chat/qml/PopupDialog.qml, gpt4all-chat/qml/SettingsDialog.qml, gpt4all-chat/qml/StartupDialog.qml, gpt4all-chat/qml/Theme.qml, gpt4all-chat/qml/ThumbsDownDialog.qml
=> New lightmode and darkmode themes with UI revamp.

gpt4all-backend/bert.cpp, gpt4all-backend/gptj.cpp, gpt4all-backend/llama.cpp.cmake, gpt4all-backend/llamamodel.cpp, gpt4all-backend/llamamodel_impl.h, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_shared.h
Now that our Vulkan backend has been merged into llama.cpp, we have a much smaller diff. This PR includes the updated llama.cpp as well as the necessary changes to make GPT4All compatible.
=> backend: update to latest llama.cpp commit

gpt4all-backend/bert.cpp, gpt4all-backend/bert_impl.h, gpt4all-backend/gptj.cpp, gpt4all-backend/gptj_impl.h, gpt4all-backend/llamamodel.cpp, gpt4all-backend/llamamodel_impl.h, gpt4all-backend/llmodel.cpp, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-bindings/csharp/Gpt4All/Bindings/LLModel.cs, gpt4all-bindings/csharp/Gpt4All/Bindings/NativeMethods.cs, gpt4all-bindings/csharp/Gpt4All/Model/Gpt4AllModelFactory.cs, gpt4all-bindings/golang/binding.cpp, gpt4all-bindings/java/src/main/java/com/hexadevlabs/gpt4all/LLModel.java, gpt4all-bindings/java/src/main/java/com/hexadevlabs/gpt4all/LLModelLibrary.java, gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/gpt4all/pyllmodel.py, gpt4all-bindings/typescript/index.cc, gpt4all-chat/chatgpt.cpp, gpt4all-chat/chatgpt.h, gpt4all-chat/chatlistmodel.h, gpt4all-chat/chatllm.cpp, gpt4all-chat/embllm.cpp, gpt4all-chat/main.cpp, gpt4all-chat/modellist.cpp, gpt4all-chat/modellist.h, gpt4all-chat/mysettings.cpp, gpt4all-chat/mysettings.h, gpt4all-chat/qml/ModelSettings.qml
This is the minimal implementation of configurable per-model partial offloading. It is up to the user to know/figure out how many layers the model has, and how many they can to load into VRAM without running out.
=> expose n_gpu_layers parameter of llama.cpp

gpt4all-chat/chatlistmodel.h, gpt4all-chat/main.cpp
Supporting Pascal GPUs is apparently as simple as relaxing the device requirements - no shader modifications necessary.
Also, fix a mistake from #1890 where clearChats is called *before* app.exec() - I obviously meant to call it after, but didn't read the code carefully enough.
Tested working on my Tesla P40 with Falcon and Mini Orca (Small) - getting about 22 tokens per second on the former and 31 tokens per second on the latter.
**edit:** Also working on my GTX 970.
=> Maxwell GPU support and crash fix

gpt4all-backend/llamamodel.cpp
This PR enables support for the following model architectures:
- Baichuan
- BLOOM
- CodeShell
- GPT-2
- Orion
- Persimmon
- Phi and Phi-2
- Plamo
- Qwen
- Qwen2
- Refact
- StableLM
These are only in the CPU inference whitelist until we know that any of them are supported on GPU.
=> llamamodel: add 12 new architectures for CPU inference

gpt4all-chat/metadata/models2.json
This PR fixes the output of Mistral OpenOrca for a user prompt such as:
```
﻿I have a question (but in Dutch)
```
Before, the model would be likely to spew random things in Dutch endlessly, and get stuck in a repetitive loop. Using ChatML makes the model behave much more like a personal assistant.
Before:
<details>
<summary>Details</summary>
</details>
After:
<details>
<summary>Details</summary>
</details>
This system prompt encourages chain-of-thought style responses, which likely improves the model's problem-solving skills, but is perhaps not a good default for a friendly model for the user to have a conversation with?
=> models2.json: use ChatML for Mistral OpenOrca

gpt4all-chat/database.cpp
Many of the formats we were attempting to read either were not plaintext, or were plaintext but not plain English. A conservative list of extensions is less likely to cause user confusion.
=> database: limit supported extensions to txt, pdf, md, rst

.circleci/continue_config.yml, gpt4all-backend/CMakeLists.txt, gpt4all-backend/llama.cpp.cmake, gpt4all-backend/llamamodel.cpp, gpt4all-bindings/python/setup.py
The CI built version 2.2.0 of the python bindings without Kompute because it was not using `--recursive` on `git submodule update`, and Kompute is now a submodule of llama.cpp.
To make GPT4All more robust to this problem:
* Fail the build if Kompute is missing instead of warning
* Allow users to pass `-DLLAMA_KOMPUTE=OFF` to explicitly build without Kompute
* Print a message on stderr if the bindings attempt to enumerate GPU devices without Kompute being built in
=> ci: fix missing Kompute support in python bindings

gpt4all-backend/llamamodel.cpp, gpt4all-chat/metadata/models2.json
Add Gemma support. Using a Q4_0 quant of this model: https://huggingface.co/google/gemma-7b-it
Also whitelist Kompute for Gemma, Phi and Phi-2, Qwen2, and StableLM, as I have tested Q4_0 quants of all of them without issue.
=> llamamodel: add gemma model support

gpt4all-backend/bert.cpp
ref https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/blob/7dbbc90392e2f80f3d3c277d6e90027e55de9125/config.json#L13
This is a quick-and-dirty fix since this code is going to be replaced anyway. It would be more correct to read layer_norm_eps when we convert to GGUF, and load that hyperparameter from the GGUF at inference time.
The difference between an epsilon of 1e-6 in LLaMA 1 and 1e-5 in LLaMA-2 created a [significant difference](https://github.com/ggerganov/llama.cpp/pull/2384) in perplexity, so they implemented this parameter to ggml_norm and ggml_rms_norm soon after LLaMA-2 came out, and until the switch to GGUF they defaulted to 5e-6, which was a suitable middleground, and allowed the user to customize the parameter at inference time via a command-line option.
The …
=> bert: fix layer norm epsilon value

gpt4all-chat/metadata/models3.json
Adds Nous-Hermes-2-Mistral-7B-DPO.Q4_0.gguf, which is the new 7b flagship model of NousResearch, to models3.json.
https://huggingface.co/NousResearch/Nous-Hermes-2-Mistral-7B-DPO-GGUF
Nous Hermes 2 on Mistral 7B DPO is the new flagship 7B Hermes! This model was DPO'd from Teknium/OpenHermes-2.5-Mistral-7B and has improved across the board on all benchmarks tested - AGIEval, BigBench Reasoning, GPT4All, and TruthfulQA.
The model prior to DPO was trained on 1,000,000 instructions/chats of GPT-4 quality or better, primarily synthetic data as well as other high quality datasets, available from the repository teknium/OpenHermes-2.5.
https://huggingface.co/datasets/teknium/OpenHermes-2.5
This is the dataset that made OpenHermes 2.5 and Nous Hermes 2 series of models.
The Open Hermes 2/2.5 and …
=> Models: Add Nous-Hermes-2-Mistral-7B-DPO.Q4_0.gguf

gpt4all-chat/metadata/models3.json
- Adds "accepts various system prompts"
- Removes system prompt
- fix whitespace
Reason for removing the system prompt:
- The current system prompt is suboptimal.
- The dataset barely contains system prompts, 
- Rudimentary small tests show that various system prompts work with this model without causing extreme "bleeding" into the responses, but since the tests were not extensive, I would like to go the "safe" route and remove the given system prompt, as it works very well without system prompt.
Co-authored-by: 3Simplex <10260755+3Simplex@users.noreply.github.com>"
=> Models: Remove system prompt of Nous-Hermes-2-Mistral-7b-DPO

gpt4all-chat/llm.cpp
On Linux, QNetworkInformation uses NetworkManager by default. I don't have NetworkManager (I use systemd-networkd), so I get no download button, *and* I get this warning on console:
```
[Warning] (Tue Feb 27 12:41:53 2024): QObject::connect(QNetworkInformation, LLM): invalid nullptr parameter
```
Change this so that the download button appears and there is no warning.
Question: Is QNetworkInformation even the right thing here? It's clearly designed to report information about how the computer is connected to the local network, which on the plus side means that the download button immediately disappears when you disable your network adapter, but I don't think it would be accurate in the case where a computer is networked but not connected to the internet (e.g. the user's ISP is …
=> chat: better handle case where network reachability is unknown

gpt4all-chat/chatllm.cpp
Chat::reset -> ChatLLM::resetContext is called when we change models. This will happen even if no model has been previously loaded.
In that case, m_llModelType is unset (contains a garbage value). regenerateResponse will attempt to read m_llModelType, causing undefined behavior (found by UBSAN) - but it seems like resetResponse was intended here anyway.
=> chatllm: fix undefined behavior in resetContext

gpt4all-chat/chatgpt.cpp, gpt4all-chat/chatgpt.h
I'm actually not sure how certain parts of this were working before #1970, namely:
- processRestoreStateFromText() - My understanding is that the LLModel would generate a new reply to both the original prompt and the original reply, because we called LLModel::prompt with the default n_predict (not zero). We were simply not *displaying* the reply (empty callback), even though it ended up in the LLModel's conversation history (m_context in the case of ChatGPT). I added fakeReply in PR 1970 because the prompt and response now need to happen within the same LLModel::prompt invocation, but as a bonus it fixes this apparent issue.
- For ChatGPT, decrementing n_past to regenerate the reply meant the *initial* new reply would be based on only the previous context, but we never actually removed …
=> chat: fix ChatGPT after #1970

gpt4all-chat/modellist.cpp, gpt4all-chat/modellist.h
A simple change that will be useful when we remove support for the SBert model that we are currently hosting. I've already made sure that the model will not be shown in the chat model list, or used for localdocs.
I think the name "removedIn" is more clear as it explicitly indicates that the model will not be listed, and if it was removed in version 2.8.0 and we are on version 2.8.0, we obviously shouldn't show the model.
=> modellist: rename "deprecated" to "removedIn", disable if equal

gpt4all-bindings/python/gpt4all/gpt4all.py
I stashed these changes last Thursday but forgot to apply them. They are necessary for proper functioning of the new prompt template syntax with the python bindings, which will look like `user_prefix {0} user_suffix assistant_prefix {1} assistant_suffix`.
=> python: more fixes for new prompt templates

gpt4all-chat/chat.cpp, gpt4all-chat/chat.h, gpt4all-chat/chatlistmodel.h, gpt4all-chat/chatllm.cpp, gpt4all-chat/chatllm.h, gpt4all-chat/main.cpp
There were some harmless warnings at shutdown with the previous code. This version of the thread joining does things a little more cleanly so the warnings don't appear.
Fixes #1921
=> chat: join ChatLLM threads without calling destructors

gpt4all-chat/mysettings.cpp, gpt4all-chat/mysettings.h, gpt4all-chat/qml/ApplicationSettings.qml, gpt4all-chat/server.cpp
#1635
For the configuration to take effect, you need to restart the application
=> feat: added api server port setting

gpt4all-chat/qml/ModelSettings.qml
…x to the currently selected chat model
As described in issue #2024 the model/character settings does not default to the currently selected chat model when opened. This commit addresses that.
#2024 
Described in #2024
=> #2024 Use the currently selected chat model as the default displayed when opening settings to update parameters

gpt4all-chat/main.qml
Added context menus for the prompt (Cut, Copy, Paste, Select All) and for the responses (Copy, Select All)
Closes #1966
https://github.com/nomic-ai/gpt4all/assets/38247289/bb340cd1-1572-4ac4-be0c-fcee95f71846
=> Add context menus to the prompt and the responses

gpt4all-backend/llamamodel.cpp
I tried to use a C++20 feature that apparently even the latest Apple clang does [not yet support](https://en.cppreference.com/w/cpp/compiler_support/20#:~:text=Parenthesized%20initialization%20of%20aggregates).
Fixes this build failure on macOS:
```
[ 67%] Building CXX object llmodel/CMakeFiles/llamamodel-mainline-default.dir/llamamodel.cpp.o
In file included from /Users/jared/src/forks/gpt4all/gpt4all-backend/llamamodel.cpp:2:
In file included from /Users/jared/src/forks/gpt4all/gpt4all-backend/llamamodel_impl.h:7:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/functional:526:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/__functional/boyer_moore_searcher.h:22:
In file included from …
```
=> llamamodel: fix macOS build

gpt4all-backend/llamamodel.cpp, gpt4all-backend/llamamodel_impl.h, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-backend/llmodel_shared.cpp, gpt4all-bindings/python/docs/gpt4all_chat.md, gpt4all-bindings/python/docs/gpt4all_faq.md, gpt4all-bindings/python/docs/index.md, gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/gpt4all/gpt4all.py
- We need token counts to be compatible with the Atlas API
- models2.json doesn't have Nomic Embed, use models3.json
- Fix missing CLS token with Bert and Nomic Bert since #2130
=> Embed4All: optionally count tokens, misc fixes

gpt4all-chat/qml/ChatView.qml
The server colors are messed up right now for some themes. This hardcodes the background and text colors for server that distinguishes it from all other chats and works for all themes.
=> Fix colors for server chat in all themes.

gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/setup.py
- Write downloads to a file ending `.part` until they are complete, verified, and synced to disk
- Verify file size and MD5 hash against models3.json, and delete the file if they don't match
- Content-Encoding must be identity for resumed downloads because of how Range requests work
This hopefully prevents incomplete downloads from making it through to llama.cpp, which tends to crash hard when that happens.
Related to #2128
=> python: improve handling of incomplete downloads

README.md
A user could read this line and reasonably interpret it to mean that models with a Q6_K ftype have Vulkan GPU acceleration in GPT4All. But what we really support are Q6_K and Q8_0 *output* tensors, which is a technical detail not worth mentioning here.
ref https://github.com/nomic-ai/gpt4all/issues/2158#issuecomment-2016879158
=> docs: fix mention of Q6_K quantization in README

gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/setup.py
=> python: use TypedDict from typing_extensions on python 3.9 and 3.10

gpt4all-bindings/python/setup.py
The 2.3.1 release of the bindings [failed](https://app.circleci.com/pipelines/github/nomic-ai/gpt4all/2130/workflows/e022c8b3-dc62-430f-8727-bdd865be7476) to upload, because it was already [built and uploaded](https://app.circleci.com/pipelines/github/nomic-ai/gpt4all/2126/workflows/51aec527-ac7b-4181-a009-50b38fdeeb47) from PR #2164.
Release version 2.3.2 of the python bindings to include all three of the intended changes (#2162, #2163, #2164).
=> python: bump version to 2.3.2 to include *all* of the bugfixes

.circleci/continue_config.yml
This change is necessary to allow documentation pages to be renamed or deleted - otherwise, they still show up under the old name.
I have no easy way of testing this (e.g. locally with --dryrun) because my AWS account does not have permission to access the `s3://docs.gpt4all.io/` bucket, so we'll just have to hope this doesn't break anything.
=> ci: use `aws s3 sync` to upload docs

gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/setup.py
This allows you to do this:
```python
from gpt4all import GPT4All
model = GPT4All('orca-mini-3b-gguf2-q4_0.gguf')
model.generate(...)
model.close()
```
or even this:
```python
from gpt4all import GPT4All
with GPT4All('orca-mini-3b-gguf2-q4_0.gguf') as model:
model.generate(...)
```
In order to free resources after using a GPT4All or Embed4All instance. This will be important for the nomic client integration, which is expected to automatically (re-)create Embed4All instances as needed, and ideally it would explicitly avoid using up all system RAM or VRAM in the process.
=> python: implement close() and context manager interface

gpt4all-chat/CMakeLists.txt
This sets the app icon properly so that when built on MacOS, the app icon shows as intended. While the favicon.icns file appears to be specified in some places, it's necessary to include it in the Resources folder and the appropriate executable manifest for it to actually be used on MacOS.
- I am unable to apply any labels myself. It would probably be an _Enhancement_
|              | Before fix  | With fix in place |
| ------------ | ----------- | ----------------- |
| Dock    | ![Screenshot 2024-03-29 at 1 06 32 PM](https://github.com/nomic-ai/gpt4all/assets/4975196/9f4405ad-027b-4930-bb99-0b16c1cbc0e5) | ![Screenshot 2024-03-29 at 1 00 18 PM](https://github.com/nomic-ai/gpt4all/assets/4975196/c2342063-7d6e-4515-ac72-c3e6116f6223) |
| Icon | ![Screenshot 2024-03-29 at 1 07 …
=> Fix to set proper app icon on MacOS.

gpt4all-backend/llmodel.cpp, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/setup.py, gpt4all-bindings/typescript/index.cc
This makes it possible to list the GPUs that can be passed to the `device` parameter of GPT4All from the python side, instead of asking users to run e.g. `vulkaninfo --summary`. This is important because the exact names of the devices are not obvious - e.g. I have a `Tesla P40` and a `NVIDIA GeForce GTX 970`.
The `mem_required` parameter is not publicly exposed yet, because it hasn't done anything since GGUF support was added.
API changes:
- GPT4All and Embed4All now only accept keyword arguments for parameters other than model_name
Other changes:
- Don't leak the array returned by llmodel_available_gpu_devices
- Remove `model` parameter from llmodel_available_gpu_devices as we can list devices without it
=> python: add list_gpus to the GPT4All API

gpt4all-backend/llamamodel.cpp, gpt4all-backend/llamamodel_impl.h, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-backend/llmodel_shared.cpp, gpt4all-bindings/python/gpt4all/__init__.py, gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/setup.py, gpt4all-bindings/typescript/index.cc
This allows a basic implementation of dynamic mode (choosing remote or local inference automatically based on expected latency/throughput) without changing the API surface too much.
The alternative would be to separate tokenization and embedding, and to keep them separate all the way to the python GPT4All API. But that seems to go against the idea of keeping the API as simple as possible.
=> python: embedding cancel callback for nomic client dynamic mode 

gpt4all-chat/chat.cpp, gpt4all-chat/qml/ChatView.qml, gpt4all-chat/responsetext.cpp, gpt4all-chat/responsetext.h
This fixes two problems with current context links:
1) When you have a long conversation and each response has context links, scrolling to the bottom of the conversation can cause the context links to no longer work for the responses at the top.
2) The context links do not work across application loads.
This patch fixes both these issues by implementing the QTextObjectInterface which allows for insertion of custom objects in the QTextDocument.
...
The second patch makes the setting for 'showReferences' simply a cosmetic toggle for the view. This way we always capture the references across restarts.
=> Fix bugs with the context link text for localdocs

gpt4all-chat/responsetext.cpp
Test markdown:
\`\`\`foo
foo
\`\`\`
\`\`\`
bar
\`\`\`
\`\`\`baz\`\`\`
How GitHub renders it:
```foo
foo
```
```
bar
```
```baz```
How GPT4All renders it on main:
How GPT4All renders it after this PR:
=> responsetext : fix markdown code block trimming

gpt4all-chat/chatllm.cpp, gpt4all-chat/database.cpp, gpt4all-chat/embllm.cpp, gpt4all-chat/modellist.cpp
- Use new `.rmodel` format for remote Nomic Embed so it can be used again.
- Fix swapped arguments in updateDocument so that documents are not reindexed on future starts if they have been updated once. On startup, this could result in excessive CPU usage and excessive token usage on the Atlas API in certain cases, e.g. when a document has been copied into the localdocs folder while GPT4All is running.
=> localdocs: small but important fixes to local docs

gpt4all-backend/llamamodel.cpp, gpt4all-backend/llamamodel_impl.h, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/setup.py
Before:
```
>>> model = GPT4All('orca-mini-3b-gguf2-q4_0.gguf', device='gpu')
llama.cpp: using Vulkan on NVIDIA GeForce GTX 970
```
After:
```
>>> model = GPT4All('orca-mini-3b-gguf2-q4_0.gguf', device='gpu')
>>> model.backend
'kompute'
>>> model.device
'NVIDIA GeForce GTX 970'
```
The message can still be enabled with `GPT4ALL_VERBOSE_LLAMACPP=1`, which is how the Metal print worked already.
=> python: do not print GPU name with verbose=False, expose this info via properties

gpt4all-chat/metadata/models3.json
Adding it above Mini Orca, because it's a similarly sized model with a more permissive license (despite the latter being built on OpenLLaMA) and likely higher quality responses.
This model uses the Llama architecture.
=> models.json: add Phi-3 Mini Instruct

gpt4all-chat/database.cpp
doc_collections_total is almost always zero on this event without this fix. At least doc_collections_total on send_message is working correctly.
=> mixpanel: fix doc_collections_total of localdocs_startup

gpt4all-bindings/golang/README.md, gpt4all-bindings/golang/binding.cpp, gpt4all-bindings/golang/binding.h, gpt4all-bindings/golang/example/main.go, gpt4all-bindings/golang/gpt4all.go, gpt4all-bindings/golang/options.go
- [ X ] I have performed a self-review of my code.
- [ N/A ] If it is a core feature, I have added thorough tests.
- [ X ] I have added thorough documentation for my code.
- [ X ] I have tagged PR with relevant project labels. I acknowledge that a PR without labels may be dismissed.
- [ X ] If this PR addresses a bug, I have provided both a screenshot/video of the original bug and the working solution.
When trying out the golang bindings, I found it couldn't build the tool because the API has changed since it's last been updated. I added the new parts of the API so it does build. I also updated the example and README to match the updated API.
If you follow the steps in the readme and try to make the bindings, you get an error because the C-api has changed.
I'd like to work more on the …
=> fixed bindings to match new API

gpt4all-chat/chatllm.cpp
Added properties to `model_load` event:
- `default_device`: what GPU would have been chosen if "Auto" were selected (unset if none available)
- `default_device_mem`: how much VRAM said GPU has in GiB, rounded down to the nearest 100MiB (e.g. `3.2`)
- `requested_device_mem`: how much VRAM the device the user has requested has in GiB
Other changes:
- Pick the GPU with the most VRAM by default, not the least (GPT4All has been wanting to use my GTX 970 instead of my P40 until now)
- Do not search for a device named "Metal" on macOS devices (there won't be any devices anyway)
- If somehow the requested GPU does not exist, use the default GPU instead of the CPU (shouldn't happen in practice but it makes the code simpler)
=> mixpanel: improved GPU device statistics (plus GPU sort order fix)

gpt4all-chat/embllm.cpp
Fixes "WARNING: Request to generate sync embeddings for non-local model invalid" when using Nomic Embed.
=> localdocs: load model before checking which model is loaded

README.md
Main problems fixed:
- The GIF at the top was from a very old version of GPT4All and did not represent how it currently looks
- Bring the official download links to the top so people are less inclined to use the offline installers
- Removed references to bindings that are abandoned and have no maintainer
- Don't call the typescript bindings "Official" as they aren't maintained by Nomic - they are a community effort
- Remove references to running on "any GPU" as we only target NVIDIA and AMD right now
=> readme: cleanup and modernization

gpt4all-chat/qml/ChatView.qml
I had some trouble understanding the context menus in the chat initially. I saw a "Copy" button and was confused when it did nothing.
What this button actually does is copy the current selection. Buttons like Copy and Cut in the context menus are now hidden when nothing is selected in order to make this more obvious.
Additionally, "Select All" on a chat message has been replaced with "Copy Message", which reduces the number of clicks required to copy an entire message from four to two.
=> ChatView: make context menus more intuitive

gpt4all-chat/qml/ChatView.qml
In the current release of GPT4All, it is possible to send a message while the LLM is generating a response, with strange results. Don't allow the user to do this.
=> chat: do not allow sending a message while the LLM is responding

gpt4all-chat/chatllm.cpp
- Use the model's prompt template instead of hardcoded Alpaca
- Use a prompt that seems to produce slightly better responses (with Llama 3 Instruct, at least)
Fixes #2281
=> chatllm: use a better prompt for the generated chat name

gpt4all-chat/database.cpp, gpt4all-chat/embllm.cpp, gpt4all-chat/embllm.h
This destroys the embedding model and thread which was leaked on exit.
=> Fix destruction and tear down of the embedding thread.

gpt4all-backend/llamamodel.cpp
Looks like we inherited a minor bug from the llama.cpp embedding example that was fixed in https://github.com/ggerganov/llama.cpp/pull/7297.
=> llamamodel: free the batch in embedInternal

gpt4all-backend/gptj.cpp, gpt4all-backend/llamamodel.cpp
Fix a crash when trying to start GPT4All with [this non-llama.cpp GGUF](https://huggingface.co/jiaowobaba02/stable-diffusion-v2-1-GGUF/blob/main/stable_diffusion-ema-pruned-v2-1_768.q4_1.gguf) installed.
Also, fix a crash when trying to load this model. Now it will display an "Unsupported file format"  error in the UI.
Fixes #2292
=> backend: do not crash if GGUF lacks general.architecture

gpt4all-chat/chatllm.cpp
This is mostly only visible on macOS, where the Metal backend has a stuttery progress report, typically reporting 0%, then some small percentage, and then quickly jumping to 100% (although not skipping the steps in between).
This change prevents a visible "Reload" prompt from showing when llama.cpp reports 0% progress.
=> chatllm: fix model loading progress showing "Reload" sometimes

gpt4all-chat/chat.cpp, gpt4all-chat/chat.h, gpt4all-chat/chatlistmodel.h, gpt4all-chat/chatllm.cpp, gpt4all-chat/chatllm.h, gpt4all-chat/qml/ChatView.qml
If you switch between chats too quickly, it can result in the UI getting into inconsistent states (e.g. a progress bar stuck at 60%) and sometimes seemingly deadlocking (which happens during the new "Waiting for model" status).
To fix UI inconsistencies:
- Move trySwitchContextInProgress, modelLoadingPercentage, and isCurrentlyLoading properties from the window to the chat so the load status always reflects the current chat
- Initialize load status at the beginning of loadModel instead of only in setModelInfo - reloadModel calls this too
- If loadModel is cancelled, quickly return instead of trying to fall back and reporting an "invalid model" error
- On load failure, instead of showing only the bottom "reload" button, show neither
To prevent quickly switching chats from queueing many …
=> chat: fix issues with quickly switching between multiple chats

gpt4all-chat/chatlistmodel.cpp, gpt4all-chat/chatlistmodel.h, gpt4all-chat/qml/ChatDrawer.qml
At startup:
- Wait until the conversationList view has been connected to the ChatListModel before adding any chats to the list. Otherwise, the initial "New Chat" tends to be scrolled just above the top of the view if the user has enough chats.
When the "New chat" button is clicked:
- If there is already a new chat, select the existing new chat instead of doing nothing. Buttons that do nothing are frustrating.
- When the new chat button is clicked, always scroll to the top of the list, so the chat is visible.
Also, make the connections to ChatRestoreThread explicitly queued. I'm pretty sure m_chats was being modified from more than one thread without this change.
=> chat: fix issues with the initial "New Chat"

gpt4all-backend/llama.cpp.cmake, gpt4all-chat/CMakeLists.txt
Apparently adding default.metallib to the executable instead of ggml-metal.metal is insufficient. You must also:
- Set the GENERATED property on the source globally, so `add_executable` doesn't complain that it isn't found
- Add a dependency on the ggml-metal target, so `make` actually generates default.metallib instead of complaining that it isn't found
=> cmake: fix Metal build after #2310

gpt4all-backend/dlhandle.h, gpt4all-backend/llmodel.cpp
I tested this change with Qt Creator on Windows. Without it, the CUDA runtime libraries are only found if they are copied into the build directory. With this change, the CUDA runtime libraries are found as long as CUDA_PATH is set correctly, which is done automatically by the CUDA Toolkit installer.
As far as the chat UI is concerned, this change only matters for users that build GPT4All from source themselves, which already requires the CUDA Toolkit. Once GPT4All is installed, the CUDA libraries are copied into the install directory.
This change should also benefit the bindings, by allowing the system CUDA libraries to be used automatically if they are installed.
=> llmodel: add CUDA to the DLL search path if CUDA_PATH is set

gpt4all-chat/cmake/installerscript.qs
I noticed that the offline installer for GPT4All v2.8.0-pre1 created `GPT4All.desktop` instead of the symlink in the applications folder. 
According to the [QtIFW docs](https://doc.qt.io/qtinstallerframework/scripting-systeminfo.html#productType-prop), systemInfo is always "macos" on macOS, not "osx".
This PR updates the installer script to also recognize "macos". This bug has presumably existed since at least #2015, when QtIFW was updated in CI. I have no idea which version of QtIFW is used to make the online installers, so I am keeping the "osx" check for backwards compatibility.
=> installer script: fix detection of macOS on newer QtIFW

gpt4all-bindings/python/gpt4all/_pyllmodel.py
This PR fixes two problems with `LLModel.init_gpu`.
The major one is a use-after-free that was uncovered by [`8dbe93d` (#2310)](https://github.com/nomic-ai/gpt4all/pull/2310/commits/8dbe93db22ccc24af25b8a3560787ae67d7579b2), which started using the `name` field of the result of `ggml_vk_get_device`. You will hit this if you try to use kompute via the python bindings after the CUDA PR.
The other one is that the error message when a GPU is not found is 1) misleading ("insufficient features" isn't implemented as those devices have *never* been listed AFAIK, and "insufficient memory" doesn't work since GGUF), and 2) formatted oddly (shows `set()` when there are no unavailable GPUs).
Message before:
```
ValueError: Unable to initialize model on GPU: 'foo'
Available GPUs: ['NVIDIA GeForce GTX …
```
=> python: init_gpu fixes

gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/setup.py
Use the official nvidia-cuda-runtime-cu12 and nvidia-cublas-cu12 pypi packages to provide the CUDA runtime.
This way, the python bindings will always be able to find CUDA on Windows and Linux, even without the CUDA Toolkit installed.
=> python: depend on offical NVIDIA CUDA packages

gpt4all-backend/llamamodel.cpp, gpt4all-chat/database.cpp, gpt4all-training/old-README.md
We have been stripping an extra token from the end of input to BERT models after the llama.cpp update in #2310. This was caught by the assertion, but only in debug builds:
```
chat: .../llamamodel.cpp:923: LLamaModel::embedInternal(...)::<lambda(...)>: Assertion `useEOS == (eos_token != -1 && tokens[n_tokens - 1] == eos_token)' failed.
[1]    17958 IOT instruction (core dumped)  build/bin/chat
```
I had changed llama_tokenize [upstream](https://github.com/ggerganov/llama.cpp/pull/6498) to use the same logic as BOS/CLS for the EOS/SEP token appended by the BERT tokenizer, but this code was still relying on the old behavior where EOS was appended unconditionally.
=> llamamodel: fix BERT tokenization after llama.cpp update

gpt4all-backend/llamamodel.cpp
n_ubatch defaults to 512, but as of the latest llama.cpp you cannot pass more than n_ubatch tokens to BERT without hitting an assertion failure.
Tested with this python code:
```python
from gpt4all import Embed4All
m = Embed4All('nomic-embed-text-v1.f16.gguf')
e = m.embed('a ' * 513)
```
Without this PR, it crashes with an assertion failure (including in release builds, since it's a GGML_ASSERT). With this PR, it succeeds.
Broken by #2310 because of https://github.com/ggerganov/llama.cpp/pull/6017
Fix based on https://github.com/ggerganov/llama.cpp/pull/6296
Fixes #2375
=> llamamodel: fix embedding crash for >512 tokens after #2310

.circleci/continue_config.yml
- We need to explicitly use the "Release" build type, or we will get plain builds without any options. Before #2310, this was the default because of some code copied into llama.cpp.cmake that IMO shouldn't have been.
- We need to build the backend with MSVC instead of MinGW in order to use CUDA.
=> ci: fix Python build after CUDA PR

gpt4all-backend/dlhandle.cpp, gpt4all-backend/llmodel.cpp
This PR improves handling of errors caused by a missing/broken nvcuda.dll. This is an example of what at least two users have seen when nvcuda.dll is incompatible with the CUDA runtime libraries shipped with GPT4All:
- If nvcuda.dll, this message is printed[^1] and GPT4All continues without CUDA:
```
constructGlobalLlama: could not find Llama implementation for backend: cuda
```
- If nvcuda.dll does not have a required symbol (which can be simulated by replacing it with an unrelated DLL), two error dialogs similar to the one in the screenshot will appear, this message is printed, and GPT4All continues without CUDA:
```
constructGlobalLlama: could not find Llama implementation for backend: cuda
```
- If nvcuda.dll is missing, you now get these warnings in the console:
```
Failed to load …
```
=> dlhandle: suppress DLL errors on Windows

gpt4all-backend/CMakeLists.txt, gpt4all-backend/gptj.cpp, gpt4all-backend/gptj_impl.h, gpt4all-backend/llamamodel.cpp, gpt4all-backend/llamamodel_impl.h, gpt4all-backend/llmodel.cpp, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-backend/llmodel_shared.cpp, gpt4all-backend/llmodel_shared.h, gpt4all-backend/sysinfo.h, gpt4all-backend/utils.cpp, gpt4all-backend/utils.h
The #includes in this repo are far from correct. This PR fixes the backend because it's common between everything, and a user has seen a missing #include cause a compilation failure after updating from gcc 13 to gcc 14. The missing/unneeded #includes were found with iwyu-tool.
gpt4all-chat has several files that barely include any standard headers at all, so some preventative maintenance might be in order for that part of the repo as well.
Fixes #2370
=> backend: fix #includes with include-what-you-use

README.md, gpt4all-bindings/python/docs/gpt4all_monitoring.md, gpt4all-bindings/python/mkdocs.yml
This PR adds doc for monitoring the GPT4All based Application. This uses OpenLIT which is essentially just a wrapper around OpenTelemetry providing one-line monitoring (traces and metrics). OpenLIT works by wrapping around the `generate` and `embed` functions in the gpt4all python sdk, collects the request and response metadata and generates traces and metrics based on the collected information. This is pretty useful for people trying to debug their LLM responses overtime, and understand performance metrics like Latency or Token usage. 
OpenLIT SDK is completly vendor-neutral(as its based on OpenTelemetry) and allows users to visualize these traces and metrics in popular observability tools like Grafana, Datadog etc
=> [Docs]: Add documentation for monitoring

.github/workflows/codespell.yml
This addresses the "Node.js 16 actions are deprecated" warning in GitHub Action runs of the codespell workflow by increasing the checkout action's version to v4.
Previous runs show the deprecation warning `Node.js 16 actions are deprecated`, e.g. on [this run](https://github.com/nomic-ai/gpt4all/actions/runs/9386591872)
=> Update checkout action to v4 in codespell workflow

gpt4all-chat/chat.cpp, gpt4all-chat/chat.h, gpt4all-chat/chatapi.h, gpt4all-chat/chatllm.cpp, gpt4all-chat/chatllm.h, gpt4all-chat/database.cpp, gpt4all-chat/database.h, gpt4all-chat/download.cpp, gpt4all-chat/download.h, gpt4all-chat/embllm.h, gpt4all-chat/modellist.cpp, gpt4all-chat/modellist.h, gpt4all-chat/mysettings.cpp, gpt4all-chat/mysettings.h, gpt4all-chat/network.cpp, gpt4all-chat/network.h, gpt4all-chat/server.cpp, gpt4all-chat/server.h
main fails to build since #2401 (oops).
The error is somewhere deep in C++ code generated by MOC, related to Database::handleEmbeddingsGenerated. It seems like you aren't allowed to use incomplete types with signals, slots, and Q_INVOKABLE methods, so this PR replaces the corresponding forward declarations with #includes.
=> chat: don't use incomplete types with signals/slots/Q_INVOKABLE

gpt4all-chat/database.cpp, gpt4all-chat/database.h, gpt4all-chat/localdocs.cpp, gpt4all-chat/localdocs.h, gpt4all-chat/mysettings.cpp, gpt4all-chat/mysettings.h, gpt4all-chat/qml/ApplicationSettings.qml
The feature is fully implemented, except for the fact that there is no place for LocalDocs settings yet, so the setting is on the Application page.
Common binary file extensions (e.g. docx) are rejected and files containing binary data are ignored (they are counted as a file with no chunks - not counting the file would require a schema change or we would have to exclude all empty files).
=> [NEW UI] configurable LocalDocs file extensions

gpt4all-chat/qml/ChatView.qml
This is using https://doc.qt.io/qt-6/qml-qtquick-listview.html#cacheBuffer-prop to actually be able to scroll the chatview. I'm at a loss for how Qt developers thought *not* using this would be acceptable in nearly any circumstance? Why wasn't this the default??
Before:
After:
=> Fix scrolling of the chat view at expense of some more memory usage.

gpt4all-chat/chat.cpp
Corrected two typos and a grammatical issue in the comments within the reset context code. Specifically:
- Changed "indictate" to "indicate"
- Corrected "me might" to "we might"
=> fix: typos in reset context comments

gpt4all-training/TRAINING_LOG.md
Corrected a typo in the training log documentation where "seemded" was changed to "seemed". This enhances the readability and professionalism of the document.
=> typo in training log documentation

gpt4all-chat/server.cpp
Add a HTTP status code 405 Method Not Allowed for each of the four handlers when the wrong method (GET/POST) is used. This mimics the OpenAI API response.
- Should I open one?
- [Mentioned in Discord](https://discord.com/channels/1076964370942267462/1096848919473946694/1260014267030044732).
```bash
$ curl -vX POST http://localhost:4891/v1/models
* Host localhost:4891 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:4891...
*   Trying 127.0.0.1:4891...
* Connected to localhost (127.0.0.1) port 4891
> POST /v1/models HTTP/1.1
> Host: localhost:4891
> User-Agent: curl/8.8.0
> Accept: */*
>
< HTTP/1.1 405 Method Not Allowed
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Content-Length: 172
<
{"error":{"code":null,"message":"Not allowed to POST on /v1/models. …
```
=> GPT4All Chat server API: add errors 405 Method Not Allowed

gpt4all-chat/translations/gpt4all_es_MX.ts
Take 2: Added the signed off by message to clean commit as requested.
Added Spanish language per [the instructions](https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-chat/contributing_translations.md). 
N/A
Behold, The Linguist!
You can open this file in Qt Linguist to verify the file will work. Linguist should auto detect it as the following:
Language: Spanish (Spain)
Country/Region: Mexico
This initial effort was aimed at Mexican (LATAM) Spanish as that is what I know, but it can also serve as a jumping off point for other Spanish-speaking countries as needed. My Spanish is also not perfect, but it will be easier for people correct any mistakes I may have made from this point forward.
=> Add Spanish (MX) Translation

gpt4all-chat/CMakeLists.txt, gpt4all-chat/main.cpp, gpt4all-chat/mysettings.cpp, gpt4all-chat/mysettings.h, gpt4all-chat/qml/ApplicationSettings.qml, gpt4all-chat/translations/gpt4all_en.ts, gpt4all-chat/translations/gpt4all_es_MX.ts, gpt4all-chat/translations/gpt4all_zh_CN.ts
This change updates the UI to allow for dynamic changes of language and locale at runtime. Right now none of the language translations are finished yet or in releasable shape so it also adds a new option to the build that enables/disables the feature. By default no translations are currently enabled to be built as part of a release.
https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-chat/contributing_translations.md has been updated to show this PR in action.
It is necessary to merge this into the main branch even though none of the translations are built by default without turning on a build flag. Without merging this into the main branch the strings will hopelessly fall behind what the translators are using. I think this is a good compromise of putting it in main but not changing any …
=> Feature: dynamic changes of language and locale at runtime issue #2644

MAINTAINERS.md
- Fix trailing whitespace - vim hates trailing whitespace
- Make GitHub usernames clickable
- Use Discord handles instead of nicknames so users can be uniquely identified and looked up
- Add jacoobes
=> maintainers: fix formatting and add jacoobes

gpt4all-chat/main.cpp
We need to set the llmodel search path before constructing the MySettings instance. Without this change, I cannot load any models when running GPT4All from the build directory as `build/bin/chat`, as GPT4All searches the current working directory for implementations instead of the intended path.
This fixes a regression in PR #2659.
=> main: set llmodel search path before initializing MySettings

gpt4all-chat/database.cpp, gpt4all-chat/qml/LocalDocsView.qml
- See notes below, there are some additional considerations.
- LocalDocsView.qml: better message and suggested fixes
- database.cpp:
- log db path
- error if Download Path doesn't exist
- Regarding: #2516
New `LocalDocsView.qml` message:
For people who run into edge cases. E.g. set *Download Path* to a non-existent directory, relaunch, then switch to LocalDocs view.
I have tried a few things since the original PR (#2652) but have not been able to reproduce the case where simply deleting the DB files fixes the problem. (Although it could always be a permissions issue.)
**I'll leave it at this PR for now, might revisit with some other improvements in a new one if I manage to pin it down.**
As mentioned in the older PR, there are some things to be wary of in general:
- As far as I …
=> Improve LocalDocs view's error message

gpt4all-chat/database.h
In previous commit 9e4991aced0571eb8db1fc07dfb7a5000932ed33 allowed case insensitive matches of file extensions. As cosmic-snow aptly pointed out this still was a case sensitive match.
=> Case insensitive compare that pairs with issue #2609

gpt4all-chat/chatllm.cpp, gpt4all-chat/chatllm.h
After #2676, attempting to load old chats crashes GPT4All. This is because the values of LLModelType, which are serialized to disk, have changed. The new builds of GPT4All misinterpret the old values of LLModelType and read bad data (Llama is loaded as ChatAPI).
This PR adds back the old enumeration values and tries to make it as clear as possible that they are not arbitrary and should not be changed.
Serialization for the GPT-J model type is also restored so GPT4All does not hit Q_UNREACHABLE on exit if there is an existing chat with one of these models.
=> chatllm: fix loading of chats after #2676

gpt4all-chat/qml/CollectionsDrawer.qml
Fixes #2573.
Make the scrollbar visible (`AsNeeded`) when there are more collections to display than what fits the height.
* #2573 
Before: see linked issue
After:
Have more collections than what fits in the right drawer in chat.
Maybe I'm missing something here, but there already was a `ScrollView` in place, just the scrollbar turned off for some reason.
So this might not be the proper way to address the issue.
=> Show scrollbar in CollectionsDrawer as needed

gpt4all-backend/llamamodel.cpp
This model actually works fine. I tried it with llama-cli before, but was thrown off by its huge default context size. With GPT4All's context size of 2K, this model works fine with CUDA. It doesn't work with Kompute due to the lack of MoE support.
***
The changelog is not merged yet, but this patch should be applied:
```diff
diff --git a/gpt4all-chat/CHANGELOG.md b/gpt4all-chat/CHANGELOG.md
index b56b993c..bc75cb6c 100644
--- a/gpt4all-chat/CHANGELOG.md
+++ b/gpt4all-chat/CHANGELOG.md
@@ -28,8 +28,9 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).
- Support translation of settings choices ([#2667](https://github.com/nomic-ai/gpt4all/pull/2667), [#2690](https://github.com/nomic-ai/gpt4all/pull/2690))
- Improve LocalDocs view's error message (by …
```
=> llamamodel: add DeepSeek-V2 to whitelist

gpt4all-backend/llamamodel.cpp
This assertion fails when [gemma-2-9b-it](https://huggingface.co/google/gemma-2-9b-it) tries to print `<end_of_text>`, which is not its EOS token. Historically, special tokens in output have been rendered as an empty string in llama.cpp and thus GPT4All has done the same.
https://github.com/nomic-ai/gpt4all/blob/54ed30937f717286083c7071e288393a3c49a769/gpt4all-chat/chatllm.cpp#L694
This is a familiar problem with other models such as Hermes 2 Pro Mistral 7B and even Llama 3 (prior to the [upstream fix](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/commit/a8977699a3d0820e80129fb3c93c20fbd9972c41)), see also #2167.
This works around the problem by printing the tokens instead of rendering them as blanks, which recently became possible with the `special` argument to …
=> llamamodel: always print special tokens

gpt4all-chat/CMakeLists.txt, gpt4all-chat/chatapi.cpp, gpt4all-chat/chatllm.cpp, gpt4all-chat/download.cpp, gpt4all-chat/download.h, gpt4all-chat/modellist.cpp, gpt4all-chat/modellist.h, gpt4all-chat/network.cpp, gpt4all-chat/network.h, gpt4all-chat/qml/AddModelView.qml, gpt4all-chat/qml/ChatView.qml, gpt4all-chat/qml/ModelsView.qml, gpt4all-chat/qml/Toast.qml, gpt4all-chat/qml/ToastManager.qml
The feature of connecting to OpenAI compatible server for chatting.
https://github.com/nomic-ai/gpt4all/issues/1243
None
TODO:
=> feat: add openai-compatible api models

gpt4all-chat/qml/ChatView.qml
Minor, cosmetic fix to the file icon which is shown as a LocalDocs source. A recent commit has allowed the file suffixes to be mixed case, this makes the displayed icon consistent, so that e.g. '.PDF' is uses the right icon, as well.
N/A
**After:**
**Before:**
Have a mixed-case file ending in your LocalDocs collection, e.g. `.PDF`, or as in the example `.pDf`
=> Fix LocalDocs file icons in sources display (mixed case)

gpt4all-chat/metadata/models3.json
Adds model support for [Qwen2-1.5B-Instruct](https://huggingface.co/Qwen/Qwen2-1.5B-Instruct-GGUF)
It is a tiny bilingual model and at the date of writing with very strong results in benchmarks (for its parameter size). It supports a context of up to 32768. Because of its model size it has very fast responses, even when doing inference on CPU. This LLM is LITERALLY for all. Since the model fits into 4GB of RAM (just barely, if the Operating System and other apps also need RAM) or alternatively into 3GB of VRAM, this will be the workhorse of the desperate and hardware poor.
- The model was trained/finetuned on English and Chinese language
- License: Apache 2.0
I got the impression the model is very task focused and this is the reason, why I chose  `Below is an instruction that describes a …
=> Models: Add Qwen2-1.5B-Instruct

gpt4all-chat/download.cpp, gpt4all-chat/download.h, gpt4all-chat/modellist.cpp
Ordering before this PR (not deterministic, but this is one possibility):
```
foo
fooa
foob
2.0
2.0.0 (greater than 2.0)
2.0.99-dev99
2.0.99-blah
2.0.99-dev0
2.0.99-rc20
2.0.99-rc2
2.0.99-rc11
2.0.99-rc10
2.0.99-rc1
2.0.99-post1
2.0.99
2.1.0-rc1
2.1.0
3.0.0-dev0
3.0.0
3.0.1-dev1
3.0.1-dev0
3.0.1
3.1.0
4.1.0
```
Ordering after this PR:
```
foo
fooa
foob
2.0.0
2.0 (equal to 2.0.0)
2.0.99-dev0
2.0.99-dev99
2.0.99-rc1
2.0.99-rc2
2.0.99-rc10
2.0.99-rc11
2.0.99-rc20
2.0.99
2.0.99-blah
2.0.99-post1
2.1.0-rc1
2.1.0
3.0.0-dev0
3.0.0
3.0.1-dev0
3.0.1-dev1
3.0.1
3.1.0
4.1.0
```
The order is now deterministic as it never ignores any part of the version. Pre-release versions compare as *less* than the stable releases that come after. ~~This means we shouldn't use post-release suffixes (e.g. …
=> chat: fix comparison of prerelease versions

gpt4all-backend/llamamodel.cpp, gpt4all-backend/llamamodel_impl.h, gpt4all-backend/llmodel.h, gpt4all-backend/llmodel_c.cpp, gpt4all-backend/llmodel_c.h, gpt4all-backend/llmodel_shared.cpp, gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-chat/chatapi.h, gpt4all-chat/chatllm.cpp
The main issue being fixed here is a CUDA crash with certain sizes of long inputs (ggerganov/llama.cpp#8798). ~~For now there is just a workaround, but upstream is working on a proper fix.~~ I cherry-picked the change from ggerganov/llama.cpp#8800 since it seems to work.
Other things I fixed while working on improving context "recalculation":
- Removed unnecessary logic guarding BOS insertion now that llama.cpp is better at knowing when it's needed
- Tried to make the token cache match n_past more often (there are still some issues involving interrupted recalculates)
- Remove now-unused "logits" and "logits_size" from the python binding's prompt context
- Fix cases where we started incorrectly inserting leading spaces again after #2694
=> backend: fix extra spaces in tokenization and a CUDA crash

gpt4all-bindings/cli/README.md
Update CLI readme.
- Mistral Instruct has been made the default a while ago with #1564
- Info from old documentation moved to the wiki page: Python-CLI
N/A
N/A
Just compare, it's outdated.
Live link to new wiki page: [Python CLI](https://github.com/nomic-ai/gpt4all/wiki/Python-CLI)
=> CLI readme: Replace default model & link to wiki

gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/setup.py
Add explicit Rosetta 2 detection to make it more clear to users when they are trying to do something unsupported.
Related to #2744, in which a user reports a GPT4All issue after seeing the AVX error we typically show in this case. Users will think: "I'm on Apple Silicon, why do I need AVX?" They may not be aware that they are using an emulated x86_64 build of Python (or think there could be a problem with that).
Tested on my M2 MacBook Pro with an x86_64 version of Python. It does detect it as expected without rejecting the standard arm64 version. Intel Macs are still supported (in theory, nobody ever tests them) because we check `sysctl.proc_translated` specifically, which should only be true under Rosetta.
=> python: detect Rosetta 2

gpt4all-bindings/python/CHANGELOG.md, gpt4all-bindings/python/setup.py
~~Leaving as draft pending merge of #2793.~~ It was merged.
This PR adds a changelog entry for the upcoming release of the python binding, and bumps the version to 2.8.0.
=> python: prepare to release v2.8.0

.circleci/continue_config.yml
It seems like `--parallel` is using too many jobs for the Linux python build and OOMing. Setting the number of jobs explicitly with `-j$(nproc)` seems to fix the issue.
=> ci: explicitly build with 4 jobs on Linux

gpt4all-bindings/python/CHANGELOG.md, gpt4all-chat/CHANGELOG.md
PR #2781 was not added to the changelog before it was merged, partially because there were no changelogs in the repo when it was opened.
=> changelogs: add PR 2781

gpt4all-chat/CMakeLists.txt, gpt4all-chat/mysettings.cpp, gpt4all-chat/mysettings.h, gpt4all-chat/translations/gpt4all_en_US.ts
This PR fixes a few outstanding issues with the translations (such as `%n file(s)` and `%n word(s)` not being transformed into their proper forms via the English translation) and includes them in the build by default.
There are a few outstanding issues, so this is marked as draft:
- "Application default" is still not translated
- Some of the translations are still unfinished, especially after #2690 (which removed some help text that I added&mdash;why?) and #2735.
- Items in the view bar no longer fit once translated into languages such as Spanish. We need to find a way to make it dynamically size to the content.
cc @jstayco @thiagojramos @SINAPSA-IC @supersonictw for translation updates. ~~It would be more organized if those necessary PRs were made into the `enable-translations` branch …
=> chat: translation tweaks

gpt4all-chat/CMakeLists.txt, gpt4all-chat/mysettings.cpp
We shouldn't attempt to load the en_US translation unless GPT4All was built with translations included. Otherwise, the default build will hit `Q_ASSERT(success);` when we attempt to install the translator, and fail.
Fixes a regression in #2797
=> chat: fix crash at startup due to missing en_US translation

gpt4all-chat/translations/gpt4all_pt_BR.ts
- Fixed button title "settings" from "Configurações" to "Config" (Making it more concise due to space constraints)
- Translated "here" in the string at line 1572
<details><summary>Details</summary>
<p>
Since Prettier (I believe it's due to it) colored the link in a dark gray, and my theme is dark, I didn't even notice it.
</p>
</details>
- And other minor changes
=> Fixed and updated some strings in pt-BR

.gitignore
CLion uses a `cmake-build-` prefix unlike Qt Creator
N/A
N/A
=> Add default CLion build folder pattern to .gitignore

.circleci/continue_config.yml
After updating the XCode used by CI, the Metal code was failing to load on Adam's Mac due to use of unsupported features.
=> ci: fix macOS target version

.circleci/continue_config.yml, gpt4all-bindings/python/CHANGELOG.md
Most importantly, the Python build should use the latest XCode and the same macOS target version as the chat UI build.
I fixed the build type for the js bindings while I was touching that area, even though they don't currently work. The other changes are just non-functional argument sorting.
Follow-up to #2813 and #2846
=> ci: use consistent build options on macOS

gpt4all-backend/CMakeLists.txt, gpt4all-backend/llama.cpp.cmake, gpt4all-chat/CHANGELOG.md
[This change](https://github.com/nomic-ai/gpt4all/pull/2802/commits/e160dff661b2de95cea025cdc8783d40dc7e2812) included in v3.2.0 introduced a build regression that caused llama.cpp to build for only the CUDA 5.2 compute architecture by default. Normally this would only be a performance regression, but for whatever reason this seems to be causing incorrect output. If this fix is confirmed, we should report the issue upstream.
Why the defaults were wrong before this PR is best explained in my [own words](https://github.com/ggerganov/llama.cpp/pull/7821) from a month ago: `enable_language(CUDA)` sets CMAKE_CUDA_ARCHITECTURES (assuming CMP0104 is enabled), so any defaults of our own must be set before this. This unfortunately means this code must be moved into the main backend CMakeLists.txt. …
=> backend(build): set CUDA arch defaults before enable_language(CUDA)

gpt4all-backend/llamamodel.cpp, gpt4all-bindings/python/CHANGELOG.md, gpt4all-chat/CHANGELOG.md
Users familiar with llama.cpp or OpenAI would expect a temperature of zero to imply greedy sampling, or at least to not produce invalid results inside of llama.cpp and crash in debug mode.
Use `llama_sample_token_greedy` just as the llama.cpp examples do in this case.
=> llamamodel: use greedy sampling when temp=0

gpt4all-bindings/python/CHANGELOG.md, gpt4all-bindings/python/setup.py
v2.8.1 will work better than v2.8.0 now that the CUDA builds have a reduced size and the pypi limit increase was approved.
=> python: release version 2.8.1

gpt4all-bindings/python/CHANGELOG.md, gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/gpt4all/gpt4all.py, gpt4all-bindings/python/setup.py
The v2.7.0 release broke Python 3.8 compatibility, and the v2.8.1 release broke Python 3.11 compatibility. Oops.
Fixes #2862
Closes #2864
=> python: fix py3.8 compat

gpt4all-chat/CHANGELOG.md, gpt4all-chat/qml/LocalDocsSettings.qml, gpt4all-chat/translations/gpt4all_en_US.ts, gpt4all-chat/translations/gpt4all_es_MX.ts, gpt4all-chat/translations/gpt4all_it_IT.ts, gpt4all-chat/translations/gpt4all_pt_BR.ts, gpt4all-chat/translations/gpt4all_ro_RO.ts, gpt4all-chat/translations/gpt4all_zh_CN.ts, gpt4all-chat/translations/gpt4all_zh_TW.ts
PR #2690 changed `getDevices()`, but failed to update the QML for the "Embeddings Device" option on the LocalDocs page to match. Since the PR had absolutely no description, I can't say I was 100% aware of what was being changed or why, so I didn't catch this.
This change prevents the "Embeddings Device" selection from showing up as blank if "Auto" was internally selected, either by default or by selecting it in a previous version. It also allows you to select the "Auto" option again after switching to something else.
For consistency with the previous PR, "Auto" is now called "Application default," and the informative description of the "Auto" option has been removed from the UI, including all translations. (I would argue that this cannot possibly be an improvement, but too much time has …
=> LocalDocsSettings: fix embedding device selection after #2690

gpt4all-chat/CHANGELOG.md, gpt4all-chat/main.cpp
On Windows, the window icon is set in the executable's metadata. macOS does not really use window icons.
But on Linux, the executable format has nothing GUI-related, so we must set the window icon explicitly when the program starts. Otherwise, you just get a placeholder that looks ugly. The window icon is used in both the title bar and taskbar in many DEs (I use XFCE).
Before:
After:
=> chat: set the window icon on Linux

gpt4all-chat/metadata/models3.json
Derank Llama 3.1 (128K) in favor of Llama 3.0 (8K) due to poor performance with the default configuration on Windows and Linux (#2768). On my P40, this is the difference between 14 t/s and 26 t/s.
A disclaimer is added to the Llama 3.1 model to try and deter users from downloading it.
It took me a little while to realize that there is no difference between the Llama 3.1 GGUFs with and without the "-128K" suffix; all of them are based on a model called Meta-Llama-3.1-8B-Instruct, which itself has 128K of context.
=> models: derank Llama 3.1 to below online models

.gitmodules, gpt4all-chat/CHANGELOG.md, gpt4all-chat/CMakeLists.txt, gpt4all-chat/src/main.cpp
Adds a new submodule of https://github.com/nomic-ai/SingleApplication which allows us to launch a single instance and guarantee further instances cannot be launched.
This is strictly a fork of the original, but we have a patch up for review here: https://github.com/itay-grudev/SingleApplication/pull/197
=> Only allow a single instance of program to be run at a time

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chat.cpp, gpt4all-chat/src/chat.h, gpt4all-chat/src/chatllm.cpp, gpt4all-chat/src/server.cpp
If server mode loads a new model, loadModel itself calls resetContext() and processSystemPrompt(). Then the server calls resetContext(), and the next promptInternal() call will once again processSystemPrompt().
loadModel() can be made to always reset the context if it returns true (which is more intuitive, IMO) if the special case for somehow queueing a switch to the already loaded model (which should only happen in some strange race, since there's also a check before queueing the signal) is moved from loadModel() to modelChangeRequested(). Then we can resetContext() as usual in loadModel() when attempting to load the already acquired model.
With this change, server mode knows the model is freshly reset (possibly including a system prompt) after loadModel(), and its explicit call to …
=> server: do not process the system prompt twice for new models

gpt4all-bindings/python/CHANGELOG.md, gpt4all-bindings/python/gpt4all/_pyllmodel.py, gpt4all-bindings/python/setup.py
On Windows, the python bindings expect the latest Microsoft Visual C++ runtime libraries to be installed to System32. This is not guaranteed, so make sure to give a clear and specific warning if they are not found.
Related to #2918
=> python: warn if Microsoft Visual C++ runtime libs are not found

.circleci/config.yml, .circleci/continue_config.yml
It's getting hard to keep track of all of the incidental CI changes I'd like to make, which mostly seem to be in PRs that are blocked on something, so I am putting them here. Changes made:
- MSVC builds should use Enter-VsDevShell to improve readability and make it easier to change MSVC versions. As commented in the script, I attempted this before and it didn't work. It turns out this was because I was missing `-arch=x64`, which is needed to get a compiler that runs as a 64-bit application (regardless of target platform).
- The apt commands on Ubuntu were hard to edit as they were not wrapped at all. Also, some of them used apt and others used apt-get&mdash;use apt-get everywhere.
- CMAKE_PREFIX_PATH on macOS cannot be ".../cmake/Qt6", or it doesn't do anything. It should just be …
=> ci: improve readability and correctness

.circleci/continue_config.yml
This PR adds ccache to the CI scripts, leveraging CircleCI's save_cache/restore_cache to persist the cache between runs. ~~Leaving as draft until #2941 is merged.~~
Without cache:
With hot cache:
The Windows build takes about 50% less time, and all builds complete in around 30 minutes instead of over an hour.
We are currently using a few gigabytes of cache for Qt, which is OK when the cache hits:
But when it misses, as it so often does, there is a +119% slowdown as it compresses and uploads Qt:
Since ccache is capped to 500MiB and is much more important, I've chosen to remove the Qt cache so it doesn't cause the ccache cache to be evicted.
We may be able to re-enable the Qt cache in the future if we think it's useful and we are able to store `~/.ccache` somewhere else, e.g. using sccache …
=> ci: use ccache to cache compiler output

.circleci/continue_config.yml, gpt4all-chat/CHANGELOG.md, gpt4all-chat/CMakeLists.txt, gpt4all-chat/build_and_run.md
WaylandCompositor is for building a Wayland compositor (server), using Qt ([ref](https://github.com/qt/qtwayland)):
> QtWaylandCompositor API:
> &nbsp;&nbsp;&nbsp;&nbsp;Enables the creation of Wayland compositors using Qt and QtQuick.
What we actually need is the Wayland platform plugin, which is not supported by linuxdeployqt (see #2306).
This reverts PR #1118.
=> chat(build): remove dependency on WaylandCompositor

gpt4all-chat/CMakeLists.txt, gpt4all-chat/src/network.cpp
This will prevent users from wasting time waiting for GPT4All to compile if their compiler does not support std::optional::transform, which we require. Success looks like this:
```
-- Checking for __cpp_lib_optional >= 202110L
-- Checking for __cpp_lib_optional >= 202110L - pass
```
Failure looks like this:
```console
$ cmake -B build -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11
-- The CXX compiler identification is GNU 11.3.0
-- The C compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-11 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C …
```
=> chat(build): add conftest for std::optional::transform

README.md, gpt4all-chat/system_requirements.md
Document the specific minimum/recommended system requirements of GPT4All and link to them in the README.
=> chat: add system requirements doc

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/qml/ApplicationSettings.qml, gpt4all-chat/src/qml/NetworkDialog.qml, gpt4all-chat/translations/gpt4all_en_US.ts, gpt4all-chat/translations/gpt4all_es_MX.ts, gpt4all-chat/translations/gpt4all_it_IT.ts, gpt4all-chat/translations/gpt4all_pt_BR.ts, gpt4all-chat/translations/gpt4all_ro_RO.ts, gpt4all-chat/translations/gpt4all_zh_CN.ts, gpt4all-chat/translations/gpt4all_zh_TW.ts
- Add translations for the new messages: `Enable Local API Server`, `cannot open "%1": %2`, and `cannot create "%1": %2`
- Fix the line wrapping of two strings in QML: One of them was hard-wrapped to a specific width which made translation difficult, and the other had lines of source code that were longer than 120 characters.
- Remove several `type="vanished"` messages that should no longer be needed.
Closes #2968
=> chat: update and improve translations for the v3.3.0 release

gpt4all-backend/README.md
=> docs: update README.md

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chatllm.cpp
In #1970, the response callback used by processRestoreStateFromText was set to nullptr because it was never used.
In #2929, this callback is now used to properly count tokens of previous assistant replies provided by the client. (The fact that processRestoreStateFromText doesn't do this causes the "regenerate" button to not work on chats freshly loaded from disk, but it's always been that way.)
The effect of this is that GPT4All throws an unhandled std::bad_function_call exception and crashes if you try to load a chat from disk and then continue it in any way. This is a regression in the v3.3.0 release, which this PR fixes.
=> chatllm: do not pass nullptr as response callback

gpt4all-chat/CHANGELOG.md, gpt4all-chat/metadata/latestnews.md, gpt4all-chat/metadata/release.json
v3.3.1 backports two important bugfixes from the main branch.
~~Leaving as draft until the installers are uploaded.~~ Done.
=> chat: release version 3.3.1

.circleci/continue_config.yml
As per [these recommendations](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177#what-do-i-need-to-do-2), CircleCI regularly deprecates older images and they can be removed at any time.
We can't rely on pinning to a particular version forever. So it's best to use the `current` tag, which will build with the latest stable version of the image. Since we're pinning to Ubuntu 22.04 LTS anyway, there shouldn't be any breaking changes with newer images - just backported bugfixes and security patches.
=> ci: use 'current' for Ubuntu image version

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chat.cpp
This bugfix comes from #3007, but that PR is complex enough as it is, so I'm splitting it out here.
PR #2929 made an incorrect change to these two lines:
https://github.com/nomic-ai/gpt4all/blob/1aae4ffe0a29ec41fadbef8098709e8a8ca7156c/gpt4all-chat/src/chat.cpp#L241-L242
To me this looked like `appendX(key, value)` was the pattern here, and that the initial response value was the prompt for no reason. I changed this to an empty string and everything still worked, so I thought I was in the clear.
Apparently not - I hadn't sufficiently tested the regenerate button, which is the sole user of the property actually set here, the response's `prompt`:
https://github.com/nomic-ai/gpt4all/blob/62bc84366bed4df3ffb6496b94b44c5a8ccb542e/gpt4all-chat/qml/ChatView.qml#L1701-L1708
All other uses of the …
=> chat: fix regression in regenerate from #2929

gpt4all-chat/translations/gpt4all_en_US.ts, gpt4all-chat/translations/gpt4all_es_MX.ts, gpt4all-chat/translations/gpt4all_it_IT.ts, gpt4all-chat/translations/gpt4all_pt_BR.ts, gpt4all-chat/translations/gpt4all_ro_RO.ts, gpt4all-chat/translations/gpt4all_zh_CN.ts, gpt4all-chat/translations/gpt4all_zh_TW.ts
Unlike #3037 this only runs the `update_translations` target, and doesn't touch any strings.
=> translations: run lupdate

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/localdocsmodel.cpp, gpt4all-chat/src/modellist.cpp
This is a reduced version of #3034 that should fix the scrolling issue that was caused by a workaround. It hopefully fixes the original problem as well, although this has not been confirmed due to difficulty reproducing the original issue.
Fixes #2943
=> modellist: fix incorrect signal use and remove invalidate calls

.circleci/continue_config.yml
There is something going wrong with the Linux build currently. LunarG has released/is releasing a new Vulkan SDK today, so let's pin to the previous version until it's sorted out.
=> ci: pin Vulkan SDK to the previous version

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/modellist.cpp
- The filename must have a version number, or we will possibly load the cache for the wrong version of GPT4All.
- The file should be stored in an appropriate folder for cache, not in the settings location.
Split from the mess that is #3034.
=> modellist: fix models.json cache location

common/common.cmake, gpt4all-backend/CMakeLists.txt, gpt4all-backend/include/gpt4all-backend/llmodel.h, gpt4all-backend/src/llmodel_shared.cpp, gpt4all-chat/CMakeLists.txt, gpt4all-chat/src/chat.h, gpt4all-chat/src/chatllm.cpp, gpt4all-chat/src/chatmodel.h, gpt4all-chat/src/database.cpp, gpt4all-chat/src/database.h, gpt4all-chat/src/modellist.cpp, gpt4all-chat/src/mysettings.cpp
I noticed the doubled semicolon issue in #3034, and decided to split it out into this PR.
I figured -Wextra-semi was worth enabling if we are going to care about this kind of thing, even though it warns about a slightly different situation (one or more semicolons where there should not be any).
And if we're going to add -Wextra-semi to the build, we may as well also add -Wall.
And that if we're going to add -Wall, we should also add some other useful warning flags that don't cause any warnings to be printed for the current code.
And we may as well fix the singular warnings about each of -Wunused-lambda-capture, -Wunused-private-field, and -Wmissing-braces so we can enable those too.
=> Establish basic compiler warnings, and fix a few style issues

gpt4all-chat/src/modellist.cpp
=> modellist: fix missing fname in modelsJsonCacheFile()

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/database.cpp, gpt4all-chat/src/database.h
Follow-up to #2986.
Some of the docx changes were not completely finished and didn't really make sense.
This fixes the dropped words at the beginning of chunks, as well as some other issues.
=> localdocs: fix regressions caused by docx change

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chatviewtextprocessor.cpp
While making #3065 I discovered this apparent copy-paste error, that caused Go syntax highlighting to never be used, with Go code highlighted as Java code instead.
This PR splits that change out in order to avoid functional changes in the warning fix PR.
=> chatviewtextprocessor: fix Go syntax highlighting

gpt4all-chat/CMakeLists.txt, gpt4all-chat/tests/CMakeLists.txt
This would allow GPT4All to be built without Python, without any special flags.
By default, the `test` and `check` targets are made available only if Python is found. Setting `-DGPT4ALL_TEST=ON` will explicitly require Python in order to run the tests. Setting `-DGPT4ALL_TEST=OFF` will prevent the tests from being built.
=> tests: make python dependency optional

.codespellrc
This fixes the codespell-related check failure after #3116.
The CircleCI failure due to no workflows running can be ignored and will be fixed in an upcoming PR.
=> codespell: update .codespellrc

.circleci/config.yml, .circleci/continue_config.yml
This workflow was removed in #2941 because it didn't have a clear purpose.
I realized recently that always running at least one workflow prevents GitHub from complaining when no files are changed.
Now that its purpose is understood, add it back with a clearer description and a more selective `when` condition (so it only runs when nothing else does).
=> Fix apparent CI failure due to "All Workflows filtered"

gpt4all-chat/CHANGELOG.md, gpt4all-chat/CMakeLists.txt, gpt4all-chat/qml/MySettingsStack.qml, gpt4all-chat/src/server.cpp
Qt 6.8 made a few significant changes:
- Breaking changes to the QHttpServer API,
- The new QTP0004 Qt CMake policy,
- And some change that affected the import of IconLabel.
This PR allows GPT4All to build and run on Qt 6.8, while maintaining compatibility with older Qt versions.
=> Fix compatibility with Qt 6.8

gpt4all-chat/CMakeLists.txt
Sometime between #1928 and now, we broke compatibility with Qt 6.4. I discovered this while [trying to use](https://github.com/nomic-ai/gpt4all/actions/runs/11449664045/job/31855669107?pr=3125) system Qt on Ubuntu 24.04 (and this was *after* making all of our references to the `<QtLogging>` header conditional).
It has been EOL since September 2023 and doesn't show up in the Qt installer by default anymore, so I don't think we should worry about it. But we should make this a hard requirement in the build script rather than failing to compile later.
=> cmake: set minimum Qt version back to 6.5

gpt4all-chat/src/chatllm.cpp
The `""_qs` operator was deprecated in Qt 6.8. It's the old way of spelling `""_s`.
=> chatllm: remove use of deprecated '_qs'

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/database.cpp
We can't return early here as nChunks could be greater than zero in which case we have to update the item statistics. They will be skipped when we generate the embeddings.
Fixes issue #2729.
=> We can't return early here as nChunks > 0

gpt4all-chat/src/chatmodel.h
I've verified that the code code compiles and I can't see any errors in runtime QML generation nor can I see any references to this in QML.
This is intended as a completely non-functional change.
=> Remove unused state from chatitems.

.circleci/continue_config.yml
Online installer builds for GPT4All and publishing new versions of the bindings should only be done on the main branch.
I made this PR because it's too easy to run the online build instead of the offline build if you aren't paying attention, and the result is mostly useless unless publishing a new version of GPT4All.
=> ci: do not run online installer or publish jobs on PR branches

gpt4all-bindings/python/CHANGELOG.md, gpt4all-chat/CHANGELOG.md
When the Jinja PR was merged (#3147), it was missing the necessary changelog entries for the chat UI as well as the python bindings. This PR retroactively adds them to v3.5.0-rc1.
=> add changelog entries for Jinja PR

gpt4all-chat/qml/ChatItemView.qml, gpt4all-chat/qml/MyToolButton.qml
- Reword the confirmation dialogs based on Andriy's suggestions
- Disable edit/redo, gray them out, and provide a helpful tooltip when they cannot be used because no model is loaded or there is a response in progress. Before, they were completely invisible.
Andriy would like to review the copy before this is merged.
=> qml: tweaks to new edit/redo buttons

gpt4all-chat/translations/gpt4all_en_US.ts, gpt4all-chat/translations/gpt4all_es_MX.ts, gpt4all-chat/translations/gpt4all_it_IT.ts, gpt4all-chat/translations/gpt4all_pt_BR.ts, gpt4all-chat/translations/gpt4all_ro_RO.ts, gpt4all-chat/translations/gpt4all_zh_CN.ts, gpt4all-chat/translations/gpt4all_zh_TW.ts
Run the `update_translations` target to prepare the translation files to be filled in for the v3.5.0 release. This should make it easier for the translators to submit their changes.
=> chat: run update_translations for v3.5.0

gpt4all-chat/metadata/latestnews.md, gpt4all-chat/metadata/release.json
Do not merge until online installers are ready.
=> chat: release v3.5.0

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/modellist.cpp
When you change a model's system message and chat template from the defaults, and then clone it, one would expect the "Reset" and/or "Clear" options on these settings to still be available (and reset to the official defaults).
Additionally, one would expect the overrides for these settings to be preserved after a restart of GPT4All if they came from overrides on the base model.
Neither of these things was working properly, because of a mistake in the clone() call - instead of copying the defaults to the defaults and the overrides to the overrides, we copied the overrides to the defaults and didn't set the overrides. So the Reset/Clear buttons were not available. And defaults are intentionally not serialized, so after a restart the clone would act like you had clicked Reset on both …
=> modellist: fix cloning of chat template and system message

.circleci/continue_config.yml
CircleCI recently updated "current" tag of the "windows-server-2022-gui" image from 2024.04.1 to 2024.12.1, which [broke nvcc](https://app.circleci.com/pipelines/github/nomic-ai/gpt4all/4023/workflows/1aec9d7f-9f40-44df-914d-4416b446eb74/jobs/22586).
>   C:\Program Files\NVIDIA GPU Computing
Toolkit\CUDA\v11.8\include\crt/host_config.h(153): fatal error C1189:
#error: -- unsupported Microsoft Visual Studio version! Only the versions
between 2017 and 2022 (inclusive) are supported! The nvcc flag
'-allow-unsupported-compiler' can be used to override this version check;
however, using an unsupported host compiler may cause compilation failure
or incorrect run time execution.  Use at your own risk.
Downgrade back to 2024.04.1 to work around this incompatibility. I tried 2024.07.1 but it had …
=> ci: downgrade Windows image to fix build

gpt4all-chat/CHANGELOG.md
This PR fixes system message detection in the chat template of models such as Mistral Instruct which handle it specially. The bug is not always easy to reproduce, but it seems to occur most reliably on Windows. The symptom is that when trying to chat with Mistral Instruct with a system prompt set, you get this instead of a response:
> ﻿Error: Failed to parse chat template: 1:1: error: Unexpected exception occurred during template processing. Exception: Jinja template error: After the optional system message, conversation roles must alternate user/assistant/user/assistant/...
The prompt template in question:
```jinja
{%- if messages[0]['role'] == 'system' %}
{%- set system_message = messages[0]['content'] %}
{%- set loop_start = 1 %}
{%- else %}
{%- set loop_start = 0 %}
{%- endif %}
{%- …
```
=> Fix Jinja2Cpp bug that broke system msg detection in templates

common/common.cmake, gpt4all-chat/CHANGELOG.md, gpt4all-chat/CMakeLists.txt, gpt4all-chat/metadata/models3.json, gpt4all-chat/qml/AddGPT4AllModelView.qml, gpt4all-chat/qml/ChatCollapsibleItem.qml, gpt4all-chat/qml/ChatItemView.qml, gpt4all-chat/qml/ChatTextItem.qml, gpt4all-chat/qml/ChatView.qml, gpt4all-chat/src/chat.cpp, gpt4all-chat/src/chat.h, gpt4all-chat/src/chatlistmodel.cpp, gpt4all-chat/src/chatllm.cpp, gpt4all-chat/src/chatllm.h, gpt4all-chat/src/chatmodel.cpp, gpt4all-chat/src/chatmodel.h, gpt4all-chat/src/codeinterpreter.cpp, gpt4all-chat/src/codeinterpreter.h, gpt4all-chat/src/jinja_helpers.cpp, gpt4all-chat/src/jinja_helpers.h, gpt4all-chat/src/main.cpp, gpt4all-chat/src/modellist.cpp, gpt4all-chat/src/modellist.h, gpt4all-chat/src/server.cpp, gpt4all-chat/src/tool.cpp, gpt4all-chat/src/tool.h, gpt4all-chat/src/toolcallparser.cpp, gpt4all-chat/src/toolcallparser.h, gpt4all-chat/src/toolmodel.cpp, gpt4all-chat/src/toolmodel.h
This is a WIP for code interpreter tool call based upon the jinja pr.
Here is the latest jinja template I'm using for [Qwen2.5-Coder-7B](https://huggingface.co/QuantFactory/Qwen2.5-Coder-7B-Instruct-GGUF):
```
{{- '<|im_start|>system\n' }}
{% if toolList|length > 0 %}You have access to the following functions:
{% for tool in toolList %}
Use the function '{{tool.function}}' to: '{{tool.description}}'
{% if tool.parameters|length > 0 %}
parameters:
{% for info in tool.parameters %}
{{info.name}}:
type: {{info.type}}
description: {{info.description}}
required: {{info.required}}
{% endfor %}
{% endif %}
If you CHOOSE to call this function ONLY reply with the following format:
'{{tool.symbolicFormat}}'
Here is an example. If the user says, '{{tool.examplePrompt}}', then you reply …
```
=> Code interpreter

gpt4all-chat/qml/ChatItemView.qml
Follow-up to #3173 that seems to fix a regression in the progress display.
This progress output is crucial when waiting minutes for a slow embedding job or prompt processing, especially on CPU.
=> qml: fix missing localdocs and prefill progress

gpt4all-chat/CHANGELOG.md
Using AFL I found that GPT4All would consistently crash with a stack-buffer-overflow when the following text is entered into the chat template box: `{% else %}{% endif %}{{`
<details>
<summary>ASAN Report</summary>
```
==567001==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffee048218 at pc 0x55555bc4873b bp 0x7fffffff6d60 sp 0x7fffffff6d50
READ of size 8 at 0x7fffee048218 thread T0
#0 0x55555bc4873a in std::__shared_ptr<jinja2::ComposedRenderer, (__gnu_cxx::_Lock_policy)2>::get() const /usr/include/c++/14.2.1/bits/shared_ptr_base.h:1667
#1 0x55555bc1c2cb in std::__shared_ptr_access<jinja2::ComposedRenderer, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get() const /usr/include/c++/14.2.1/bits/shared_ptr_base.h:1364
#2 0x55555bbe6d80 in …
```
=> jinja2cpp: update submodule for else/endif crash fix

gpt4all-chat/CHANGELOG.md, gpt4all-chat/main.qml, gpt4all-chat/src/chatlistmodel.cpp, gpt4all-chat/src/chatlistmodel.h
This allows GPT4All to remember its chats on reopening if it was closed with Cmd-Q on macOS.
Without this PR, closing the window by clicking the red dot will show a message like "serializing chats took 0 ms, saved 0 / 4 chats" in the console and save the chats, while Cmd-Q will not.
With this PR, chats are saved once in either case.
Fixes #3367
=> Save chats on quit, even if window isn't closed first

.circleci/continue_config.yml
This allows us to share secrets between the Community and Enterprise editions without maintaining multiple sets of environment variables between the project configurations. As a bonus, only jobs that need access to secrets will have them in their environment, providing increased security.
The 'gpt4all' CircleCI context already exists and contains the necessary environment variables for Community. Enterprise has always used this context, with the intent to share it with Community edition.
Once this PR is merged, we can remove the environment variables from the Community edition project settings in CircleCI since they will no longer be needed.
=> ci: use the shared 'gpt4all' context for environment variables

gpt4all-chat/CHANGELOG.md
This fixes the crash when you enter this text in the chat template field:
```
{{ a["foo"(
```
The crash was caused by this assertion failure:
> nonstd/expected.hpp:2173: nonstd::expected_lite::expected<T, E>::value_type& nonstd::expected_lite::expected<T, E>::operator*() & [with T = std::shared_ptr\<jinja2::ExpressionEvaluatorBase\>; E = jinja2::ParseError; value_type = std::shared_ptr\<jinja2::ExpressionEvaluatorBase>]: Assertion `has_value()' failed.`
=> jinja2cpp: update submodule for partial subscript crash fix

.circleci/continue_config.yml
The Windows ARM PR (#3385) was merged without resolving a conflict with the PR to share secrets with Enterprise (#3392).
This should fix the build which is currently failing because of this: https://app.circleci.com/pipelines/github/nomic-ai/gpt4all/4164/workflows/9df52149-2582-4db6-ae12-13877c916ca7/jobs/23327
=> ci: add missing context to Windows ARM builds

gpt4all-chat/CHANGELOG.md
It turns out that the reason #3372 was needed was that `if not add_generation_prompt is defined` was meant to be parsed as `if not (add_generation_prompt is defined)`, which is how it works in Jinja2Cpp and also how those operators work in the Python language [itself](https://docs.python.org/3/reference/expressions.html#operator-precedence) ('is' binds more strongly than 'not').
But Jinja2Cpp parsed that as `if (not add_generation_prompt) is defined`, which when read that way is nonsense&mdash;it will always be true, so the conditional will always be executed.
With this change, the operator precedence is corrected, so Jinja2Cpp is able to interpret these expressions in the expected manner. This leaves list slicing as the primary limitation preventing Jinja2Cpp from being compatible with …
=> jinja2cpp: update submodule for 'not X is defined' fix

.circleci/continue_config.yml, gpt4all-chat/CMakeLists.txt
On Sequoia, GPT4All builds made in CI crashed after #3391.
My local builds were signed successfully because I was not using `-DBUILD_UNIVERSAL=ON`. I do not really understand why that option affects code signing, but that's not important. This does however explain why I didn't catch this when I originally tested the build and verified that it was signed, even though I never run the `install` target.
What is important is that the way #2443 signs binaries in a way that is antithetical to the spirit of CMake: Instead of each task taking input and producing separate output files, forming an explicit dependency, there is a task manually added to the `install` target that signs the *source* binaries in the build dir *before* copying them, *in place*.
This means that running the `install` target …
=> ci: fix macOS codesigning

gpt4all-chat/metadata/latestnews.md, gpt4all-chat/metadata/release.json
These are the release notes for v3.7.0. This PR is not ready to merge yet because the online installers have not been fully uploaded.
=> chat: release version 3.7.0

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chatllm.cpp
We've had a regression since 3.5.x where the model was not using localdocs for N > 1 server api message. We weren't taking into account the idiosyncratic way the server uses the chatmodel so that we require an offset when updating the sources.
=> Fix regression while using localdocs with server API.

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/codeinterpreter.cpp
See [the docs](https://developer.mozilla.org/en-US/docs/Web/API/console/log_static).
#3371 causes the `console.log(msg)` case to throw an error, which is overly restrictive.
Only throw an error if there are at least *two* arguments and the first one is a string, which is the case that we definitely cannot handle correctly without additional code.
Also make sure the zero-arg case is a no-op, to be consistent with standard JavaScript.
=> codeinterpreter: permit console.log with single string arg

.circleci/continue_config.yml
See the commits for details. This PR has two main goals:
- Do not automatically sign and notarize non-release builds, since signing implies that we are confident in the contents of the executable&mdash;but this is not always the case, e.g. when building test installers for a community-submitted PR. This process can still be approved manually.
- Automatically build and sign all installers when a tag starting with `v` is pushed to the main branch.
The former appears to be set up correctly: see [here](https://app.circleci.com/pipelines/github/nomic-ai/gpt4all/4214/workflows/e98c11bd-03d7-47ac-8501-43c1dbbf673e) (offline) and [here](https://app.circleci.com/pipelines/github/nomic-ai/gpt4all/4214/workflows/ae05ce00-b7fb-4cba-b102-eec2a6fe1de4) (online). The latter can't easily be tested until …
=> ci: selective signing and automatic release builds

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chatllm.cpp, gpt4all-chat/src/jinja_replacements.cpp
This PR adds DeepSeek-R1 Qwen support by:
- Rebasing llama.cpp on a slightly newer upstream commit (ggerganov/llama.cpp@a39ab216a from Oct 2 instead of ggerganov/llama.cpp@95bc82fbc from Sep 26)
- Cherry-picking the [one-line change](https://github.com/nomic-ai/llama.cpp/commit/b06658d366abe3cea92f4e868db72165531a74da) required to load the DeepSeek GGUF
- Adding a prompt template substitution that doesn't rely on things like `namespace` and `str.split` which Jinja2Cpp doesn't implement
- Implementing a `regex_replace` function compatible with [others](https://docs.saltproject.io/en/3006/topics/jinja/index.html#regex-replace) seen in the wild to support the necessary text manipulation in the DeepSeek template.
Tested on DeepSeek-R1 Qwen 7B. Will update with results with 14B and 32B soon. …
=> Support DeepSeek-R1 Qwen

.circleci/continue_config.yml
When we initially attempted to deploy GPT4All v3.7.0, we could have benefited from these checks. The installer functioned on macOS but the installed binary was not correctly signed (#3408).
=> ci: verify that installers we build function and are signed

gpt4all-chat/CHANGELOG.md, gpt4all-chat/qml/ChatItemView.qml, gpt4all-chat/src/chat.cpp, gpt4all-chat/src/chat.h, gpt4all-chat/src/codeinterpreter.cpp, gpt4all-chat/src/codeinterpreter.h, gpt4all-chat/src/tool.h
Also allow them to run as long as user permits.
We're currently blocking the gui thread for the code interpreter. This fixes that and also gives the user control over how long the toolcall can take. This is useful for prompts like:
`find the first 10 numbers that meet all these criteria: (1) they are part of the fibonacci sequence, (2) they are a prime number plus 7`
Which was mentioned [here](https://github.com/nomic-ai/gpt4all/issues/3355) and is computationally incredibly expensive with naive code.
=> Don't block the gui thread for tool calls

.circleci/continue_config.yml
With the CI changes made in this PR, the "schedule" workflow (and only that workflow) will run when the GPT4All CI pipeline is triggered via a schedule.
Then we can configure a trigger as documented [here](https://circleci.com/docs/set-a-nightly-scheduled-pipeline/) to start making nightly builds.
Currently this workflow simply builds and signs the offline installers, but it can be adjusted as needed.
=> ci: build offline installers when pipeline is scheduled

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chat.cpp, gpt4all-chat/src/chatllm.cpp, gpt4all-chat/src/chatmodel.h, gpt4all-chat/src/toolcallparser.cpp, gpt4all-chat/src/toolcallparser.h
DeepSeek often ends responses to messages such as "hello" with an emoji.
We were parsing each token of output from the LLM as a QString. Tokens do not necessarily form complete code points, and can represent individual bytes. So we were getting a series of question marks instead of an emoji:
<br/>
<br/>
<br/>
The changes in this PR are sufficient to fix that:
=> chat: fix emoji corruption

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chatllm.cpp, gpt4all-chat/src/chatmodel.h
Fixes https://github.com/nomic-ai/gpt4all/issues/3445
When using tool calling or reasoning (e.g. DeepSeek) and LocalDocs, the second response would be an error like this:
```
Error: item at index 3 is not a prompt
```
Which is accurate&mdash;the item at (global) index 3 is the about-to-be-generated response, not a prompt.
This was caused by using the index in the flattened list instead of the index of the parent ChatItem in its container. The cleanest solution is to just store the index of the original ChatItem parent in the MessageItem, so we don't have to try and look it up later. This simplifies the query prompt lookup, removing the `startOffset` addition (since the index is now saved *before* we slice the list for the local server).
I have tested and confirmed that it now uses the …
=> Fix index used by LocalDocs when tool calling/thinking is active

gpt4all-chat/CHANGELOG.md, gpt4all-chat/CMakeLists.txt, gpt4all-chat/cmake/config.h.in, gpt4all-chat/src/config.h.in, gpt4all-chat/src/main.cpp
The Direct3D 11 scene graph backend shows rendering artifacts on my Windows 11 ARM laptop.
System Model: Dell Latitude 7455
SoC: Snapdragon X Elite X1E-80-100
OS: Windows 11 Pro 24H2 build 26100.2894
GPU: Qualcomm Adreno X1-85
GPU Driver Version: 31.0.80.0 (10/28/2024)
They look like this:
Also, the (hidden) LocalDocs drawer sometimes pops in and out of visibility while the model is generating a response.
None of these issues happen on the Direct3D 12 backend, so let's use that by default on Windows ARM.
=> chat: work around Direct3D 11 rendering artifacts on win11 arm

gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chat.cpp, gpt4all-chat/src/chatllm.cpp, gpt4all-chat/src/chatllm.h, gpt4all-chat/src/modellist.h, gpt4all-chat/src/toolcallparser.cpp, gpt4all-chat/src/toolcallparser.h
By separating the "tool call" parsing from the chat model using a class abstraction, we are able to reuse the think tag parsing code. Reusing it for the chat name and follow-up generation prevents it from ending up in the response on screen, which should never happen.
Some additional tweaks are made to the name generation so at least Meta Llama 3 generates reasonable chat names (reusing changes from #3172). The DeepSeek-R1 distillations are finicky and will require more advanced prompting techniques to get consistent results.
=> Ignore DeepSeek-R1 "think" content in name/follow-up responses

gpt4all-chat/CHANGELOG.md, gpt4all-chat/deps/CMakeLists.txt, gpt4all-chat/src/database.cpp, gpt4all-chat/src/main.cpp
With -DGPT4ALL_USE_QTPDF=OFF, we hit an embarrassingly misplaced call to `FPDF_DestroyLibrary()` after the first PDF is read. This prevents further use of PDFium without a call to FPDF_InitLibrary, which never happens.
So after we read a few PDFs, this causes a crash. The fix is to destroy it at shutdown instead. There is also a change here to improve the exception safety of m_page, which might result in a double-free otherwise.
=> Fix PDFium abuse that leads to a crash on Windows ARM

gpt4all-backend/src/llamamodel.cpp, gpt4all-chat/CHANGELOG.md
Those two model architectures are supported in llama.cpp and technically in GPT4All 3.8.0 as well, but they have to be whitelisted to make them accessible to users, so do it.
Here are the models:
- https://huggingface.co/allenai/OLMoE-1B-7B-0924-Instruct
- https://huggingface.co/ibm-granite/granite-3.1-3b-a800m-instruct
They are really small and not the brightest, but very fast. I am hoping to make use of them for sentence similarity search with the LocalDocs feature. There was also a user that wanted to have tiny LLMs for educational purposes in Africa, because of hardware constraints.
Because they are so fast and tiny and not the brightest, not having them supported on the compute backend could be argued to be justified. They are compatible with the Cuda backend though, so that's good.
=> Add olmoe and granitemoe architecture to whitelist

gpt4all-chat/metadata/latestnews.md, gpt4all-chat/metadata/release.json
Currently blocked on:
- ~~Upload of installers~~ (done)
- ~~Testing of installers~~ (done)
=> chat: release version 3.9.0

gpt4all-backend/src/llmodel.cpp, gpt4all-chat/CHANGELOG.md, gpt4all-chat/src/chatmodel.h, gpt4all-chat/src/database.cpp, gpt4all-chat/src/database.h, gpt4all-chat/src/embllm.cpp, gpt4all-chat/src/logger.cpp, gpt4all-chat/src/logger.h, gpt4all-chat/src/network.cpp, gpt4all-chat/translations/gpt4all_ro_RO.ts
The theme of this PR is things I noticed while trying to make Windows ARM more stable. None of them seem to affect the official releases in practice.
- AddressSanitizer detected a stack-use-after-return in database.cpp, which is now fixed.
- The backend no longer crashes if one of the search dirs does not exist (related to #3417)
- Builds against the debug version of Qt, which is the default on Windows debug builds, were complaining about a call to setParent from the wrong thread. This is fixed.
- The Visual Studio build (not used in CI) was failing due to a duplicate string in gpt4all_ro_RO.ts, which has been fixed.
- Debug builds were crashing when inconsequential network requests were failing, such as Mixpanel. This is now reduced to a warning when the QNetworkReply reports an error …
=> Misc fixes for undefined behavior, crashes, and build failure

gpt4all-chat/CHANGELOG.md, gpt4all-chat/qml/ChatItemView.qml, gpt4all-chat/src/chatllm.cpp
1) If the think tag is empty don't show it at all
2) Always trim the responses for whitespace so if the model generates
<think>blah</think>
[new line]
final response
The finale response is trimmed of the newline.
=> Fix spacing issues with deepseek models:

gpt4all-backend/src/llamamodel.cpp, gpt4all-chat/CHANGELOG.md
Adds granite architecture to model whitelist
Resolves https://github.com/nomic-ai/gpt4all/issues/3159
Related to https://github.com/nomic-ai/gpt4all/pull/3471 and https://github.com/nomic-ai/llama.cpp/commit/11f734c3b0334dbae4823b4a7467764e447fc6d6
=> Add Granite arch to model whitelist

.circleci/continue_config.yml, gpt4all-backend/CMakeLists.txt, gpt4all-chat/CHANGELOG.md
It is possible that our llama.cpp backend is compatible with CUDA compute 5.0 GPUs such as the GTX 750 from 2014. This was not believed to be the case before since upstream llama.cpp has not mentioned this officially that I know of, but apparently ollama includes compute 5.0 support in its CUDA 11 backend. We are also using CUDA 11, so it is worth a shot.
Fixes #3481
=> backend: build with CUDA compute 5.0 support by default

gpt4all-chat/CHANGELOG.md, gpt4all-chat/translations/gpt4all_zh_CN.ts
Fix spelling mistake in Chinese translation.
=> Translations: Improve Chinese translation
